### ISSUE TITLE
Binary Compression

### ISSUE THREAD

**Issue by josiah47** [create3000/titania#1]
Is there any plans to have x3dtidy implement binary compression if it doesn't already?
http://www.web3d.org/wiki/index.php/X3D_Binary_Compression_Capabilities_and_Plans

End goal for us is speeding up x3dom rendering.

http://www.x3dom.org/pop/

**Comment by create3000** [comment]
It is not yet very clear to me how to implement binary compression, thats why there is no support. Yes this would be nice and would make Titania more complete. The samples of x3dom are impressive but it would be better if they have autogenerated normal support ...

**Comment by create3000** [comment]
... autogenerated normal support depending on creaseAngle value.

**Comment by create3000** [comment]
For an easy to handle and widely understandable compression you can gzip your files and name it *.x3dz or *.x3d.gz.
