### ISSUE TITLE
Reverse Routes

### ISSUE THREAD

**Issue by josiah47** [create3000/titania#10]
Is it possible to define a route between 2 transform groups BUT the one group does the opposite of the other? so if group one rotates 1 degree, group two would rotate -1 degree?

**Comment by create3000** [comment]
Yes, this is possible if you connect between the Transform nodes a Script node. Connect the first Transform's rotation to a Script node, do some calculations and then output the result, and connect the Script's modified rotation to the second Transform. Below there is a schematic description of this case:

---> (first) Transform.rotation_changed ---> Script.set_rotation ... (your logic here within the script) ... Script.modifiedRotation_changed ---> (second) Transform.set_rotation

**Comment by create3000** [comment]
There are two much more simpler approaches for this case:
1. Create a parent Transform over the second node and rotate this new Transform about 180 degrees.
2. Use negative scale values for the second node.
