### ISSUE TITLE
when saving a world the value of the last eventin of a field is saved as its actual value.

### ISSUE THREAD

**Issue by splace** [create3000/titania#100]
example of a problem this causes (what happened to me): 

if you have animations running and have a script to stop them, by setting an endTime on a TimeSensor, that endTime is saved and the world, when reloaded, is not animating anymore. this happens without any editing or you being aware of it happening.

**Comment by create3000** [comment]
When you write a Script that sends events, it modifies the world and that is saved. If you want that the animation is running at startup, write another Script that sends on initialize a event that starts the animation.

**Comment by splace** [comment]
the actual problem this causes is more apparent for endTime, since after saving the animation wont start and the user may be working on some other part of the world and would not expect to have unrelated things brake, very hard to debug and will continuously need fixing after every save.
