### ISSUE TITLE
sounds playing when world opened with pause on.

### ISSUE THREAD

**Issue by splace** [create3000/titania#102]

**Comment by create3000** [comment]
If you have the Sound node selected and the Sound Editor open the node will always be enabled to play sounds even if 'pause' is active.

**Comment by splace** [comment]
> If you have the Sound node selected and the Sound Editor open the node will always be enabled to play sounds even if 'pause' is active.

when world OPENED no selection or opening dialog.

if you press play, sounds still play, if you press pause then they stop.

if you restart titania and the previous world is automatically loaded then sounds start immediately. 

i would guess you have tested with a sub-set of sound parameters. 

see  https://splace.github.io/3d/2005/ship/scene.wrl
