### ISSUE TITLE
unable to add fields to script

### ISSUE THREAD

**Issue by splace** [create3000/titania#107]

**Comment by create3000** [comment]
You can add fields to a Script node as following: select the Script node, open the Node Editor, select Node Properties (the first tab on the right side), select the 'User-Defined Fields' tab at bottom, add/remove Script fields.

**Comment by splace** [comment]
OK, i was never going to find that.

FYI i sent 20mins guessing then another 20min reading docs, before giving up.

**Comment by splace** [comment]
how about a button on the script editing control to open that control?
