### ISSUE TITLE
Inline Reload

### ISSUE THREAD

**Issue by josiah47** [create3000/titania#11]
Is there a way to just reload an inline file and not the whole top level file? so if you change the material in an inline file you can reload it in the master scene?

**Comment by create3000** [comment]
No this is not possible. But you can directly edit the Inline node/file.
1. Move your mouse over the Inline nodes name within the Outline Editor.
2. Right click to show up the context menu.
3. Select »Set as current scene«
You can now change the material or other thing directly within the Inline node.
To go back to your parent scene, use the small arrow buttons located directly above the tree view.

**Comment by create3000** [comment]
This is now possible since a while. In the inline editor there is a reload button and it is also possible to set the inline a current scene for editing purposes.

**Comment by create3000** [comment]
The current version should solve this issue.
