### ISSUE TITLE
routing script string eventout to text node not always working.

### ISSUE THREAD

**Issue by splace** [create3000/titania#111]
same example code as  #109 

this is 100% working in x-ite but only intermittently in Titania, can't find any pattern as to when it works/doesn't.

**Comment by create3000** [comment]
Looking at the code and image this should be the right visual output, because non renderable characters like '\n' will be rendered as rectangle.

**Comment by splace** [comment]
you misread my report. sometimes titania displays 'default'.

i have done some work to investigate; it happens with some combination of pause/save/load/shutdown/startup/play, the world becomes 'stuck' , this may be a consequence of the design decision causing #100  

at least x-ite is OK.

**Comment by create3000** [comment]
It is important to make Scripts work, that 'play' is on. If the browser is in 'pause' mode, than Script will not send events and are not processed.

**Comment by splace** [comment]
i am as certain, as i can be, that i did not have pause on and remember trying turning pause on/off (after my mistake previously with this, i check it first.)

but, if it exists, this bug is hard to demonstrate, if i can not generate it on demand and can only show it by recording a movie. even then it is not much help to you without a pattern for it's occurrence.

**Comment by splace** [comment]
[feature request]

if the button (or the underline) were to flash when paused it would be clear and visually distinctive. (blinking, paused things, is generally quite a common idea)

**Comment by splace** [comment]
i think i have it...

its the initialize() function; its only called on startup and not when you edit the world, so if you edit anything that is in anyway effected by that function, you have an 'impossible' world, (one that could never exist 'normally', in x-ite or any browser.) until you next load!

i think this could be renamed and reopened?
