### ISSUE TITLE
TimeSensor added using 'add node' context menu not working.

### ISSUE THREAD

**Issue by splace** [create3000/titania#114]
starts working when world saved and reloaded.

**Comment by create3000** [comment]
Assume 'play' is on, I added a TimeSensor, toggled loop to TRUE and the TimesSensor is running.

**Comment by splace** [comment]
yes, i can not now reproduce. 

it was repeatable and i did toggled 'play' on/off, (remembering my earlier mistake.) several times. if it is 'real' it will reproduce at some point.

**Comment by splace** [comment]
could this be #111?
