### ISSUE TITLE
Browser context menu Layout tools check box control not working.

### ISSUE THREAD

**Issue by splace** [create3000/titania#115]
![Screenshot from 2019-06-19 16:26:21](https://user-images.githubusercontent.com/1234848/59778842-23427200-92af-11e9-8c8f-3ac78143665d.png)

**Comment by splace** [comment]
4.5.8 still not working for me.

example: open new world, has grid on, try turning off with menu, nothing happens.

**Comment by create3000** [comment]
Now I have understood what is wrong. Should be fixed now.

**Comment by splace** [comment]
i have just noticed something else ...(i am trying to make a definitive test case for sound files issues)

after trying to switch on the grid, using the context menu, (the box is now ticked but no grid), other visibility stuff is not longer working, for example the 'show sound' fails to display anything (hope this was already fixed.)

**Comment by splace** [comment]
confirmed fixed.
