### ISSUE TITLE
timedependent node types - indicate in outline UI non-standard fields.

### ISSUE THREAD

**Issue by splace** [create3000/titania#118]
i think its clearer if these fields were singled-out...

AudioClip; 
* cycleTime
* speed
* enabled.

MovieTexure;
* cycleTime
* pitch
* enabled

though useful, using these would mean creating a non-complaint world.

**Comment by create3000** [comment]
The are additional fields to unify timedependent/soundsource nodes. X3D mean Extensible 3D, and this is a Titania/X_ITE extension.

**Comment by create3000** [comment]
These fields were necessary in the past for internal handling. I think it could be possible to remove these.

**Comment by splace** [comment]
> X3D mean Extensible 3D

my sense of the name would be; "X3D is 3D encoded using an eXtensible Markup Language format"

as i say i can see the logic, but still;

> would mean creating a non-complaint world.

if people use them, to route too say, then their world depends on them and so wont work elsewhere, which would be a shame.

**Comment by create3000** [comment]
MovieTexture has also a pitch field, see http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/texturing.html#MovieTexture.

**Comment by create3000** [comment]
Both fixed in Titania and X_ITE.

**Comment by splace** [comment]
confirmed fixed.
