### ISSUE TITLE
TimeDependentNode elapsedTime incrementing without media present.  (until saved/loaded)

### ISSUE THREAD

**Issue by splace** [create3000/titania#119]
a MovieTexture made by 'new node' does not run when loop set TRUE, play/pause no effect. 

just opening "Node editor/sound" starts it running, but then play/pause will not stop.

**Comment by create3000** [comment]
I created a scene and used 'Add Node' to create a Movie Texture and it is running.
Steps to reproduce:
1. Check if 'play' is on.
2. Click on 'New Scene'
3. Save scene.
4. Click on Box to create a box with transforms.
5. Use 'Add Node' to create a MovieTexture.
6. Drag & Drop MovieTexture to Appearance of Box
7. Change url of MovieTexture to 'film6.mp4', assume it is in the same folder
8. Toggle loop field of MovieTexture to TRUE
9. MovieTexture is running

film6.mp4

[film6.zip](https://github.com/create3000/titania/files/3316462/film6.zip)

**Comment by create3000** [comment]
Please describe the exact steps to reproduce, this would help very much. See example above.

**Comment by splace** [comment]
here i make two time dependent nodes,(for comparison) AudioClip behaves as expected, MovieTexture differently.

(i should have said earlier, the nodes are created with world paused.)

![Peek 2019-06-22 16-13](https://user-images.githubusercontent.com/1234848/59965895-24bca600-950c-11e9-9f15-a673e83893e1.gif)

**Comment by splace** [comment]
when i investigated what happens when the world is saved and reloaded, i find AudioClip also becomes 'stuck'

(note: node is not created with pause on, but loop is set to true with pause on.)


![Peek 2019-06-22 16-36](https://user-images.githubusercontent.com/1234848/59966013-cee8fd80-950d-11e9-8a20-b4a1e09e8d75.gif)

**Comment by splace** [comment]
i can see that without a URL there is no duration, but then why does AudioClip run (and stop running when world paused) and why does MovieTexture run (and not stop running when world paused) when the Node editor is opened and when created with pause off?

**Comment by splace** [comment]
may not be related, but i notice when movietexture has been running it showing clones that arn't there...
( the number of them jumps up/down)

![Screenshot from 2019-06-22 17:08:44](https://user-images.githubusercontent.com/1234848/59966202-a6aece00-9510-11e9-92f9-15df8f3cf548.png)

**Comment by splace** [comment]
done some reading of the spec....

it seems elapsedTime is intended to increment when the content is actually playing, i think, this is so that events in the world can be synchronised with particular moments in the media.

but this...

>  The elapsedTime outputOnly field delivers the current elapsed time since the TimeSensor was activated and running, cumulative in seconds and not counting any time while in a paused state. 


 is the only reference, and its specific to TimeSensor, so strictly nothing is said about what happens to elapsedTime for either AudioClip or MovieTexture?


so, using the best-guess above, in all these cases, (without url's) it should not be running and only start when a url is loaded and has started playing. (which if a url is updated by a script would need to allow for any download delay.)

given that this seems fine after a save/load (elapsedTime not running) then this is more on feature request than a bug.

**Comment by splace** [comment]
confirmed fixed.
