### ISSUE TITLE
compiling: which gcc version ?

### ISSUE THREAD

**Issue by andreasplesch** [create3000/titania#12]
I am trying to compile on a distro other than Ubuntu. configure finishes without complaints but then make immediately aborts complaining about this CXX flag:

-std=c++14

I use gcc version 4.8.5. It looks like this flag is only supported >gcc 5 ? Is it needed ? What version is recommended ? Other tips for compiling ?

Thanks.

**Comment by andreasplesch** [comment]
Since it looks like as if titania is compiled on Ubuntu Wily and Xenia, gcc > 5.3 is used:
http://packages.ubuntu.com/wily/gcc
http://packages.ubuntu.com/xenial/gcc
I may give this a try.
ok, since my system libs are gcc < 5, it does not look promising since there seem to be incompatibilities linking with gcc > 5 compiled code.

**Comment by create3000** [comment]
The latest trunk version of Titania is compiled with gcc version:
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) 
Should test this in configure.ac ...

**Comment by andreasplesch** [comment]
Thanks. Looks like I have to wait until gentoo switches over to gcc>5 .

**Comment by create3000** [comment]
I have decided to switch to c++14 version this Ubuntu release, as I wants to keep Titania up to date, that's my intention. I still wait one or two gcc releases until I use a new feature switch, but c++ in its new versions provide interesting and very useful features that makes the live of a programmer easier, and programming makes more fun. I think this was a good choice, and I hope you doesn't have to wait so long until gentoo support gcc v5.

**Comment by andreasplesch** [comment]
Understood. There is an upgrade path for my system but it looks like it would be lot of work since many libraries and apps would need to be replaced. I will probably try a VM with Ubuntu, instead.

**Comment by create3000** [comment]
What Linux distribution do you use?

**Comment by andreasplesch** [comment]
I use Gentoo. https://wiki.gentoo.org/wiki/Upgrading_GCC
