### ISSUE TITLE
[script] vrml types constructors not available outside functions.

### ISSUE THREAD

**Issue by splace** [create3000/titania#121]
see

http://x3dgraphics.com/examples/X3dForWebAuthors/Chapter09EventUtilitiesScripting/newECMAscriptTestIndex.html

console:

> ReferenceError: "SFString is not defined"

**Comment by create3000** [comment]
This is a bug in the example.

The spec defines no SFString object, see http://www.web3d.org/documents/specifications/19777-1/V3.3/Part1/functions.html#FieldServices.

Scalar types like SFBool, SFDouble, SFFloat, SFInt32, SFString, SFTime are converted to ECMAScript native types Boolean, Number, String, see http://www.web3d.org/documents/specifications/19777-1/V3.3/Part1/types.html#X3DFieldToECMAScriptConversion and http://www.web3d.org/documents/specifications/19777-1/V3.3/Part1/types.html#t-t-X3DTypesToECMAScriptTypes.

**Comment by splace** [comment]
OK, good
