### ISSUE TITLE
FogCoordinate effect not as required.

### ISSUE THREAD

**Issue by splace** [create3000/titania#122]
FogCoordinate values are having an effect but the avatar position does also...

(see example- has blue fog)

![scene](https://user-images.githubusercontent.com/1234848/60690645-cd7de480-9ec0-11e9-9085-9c105964fd84.png)

closer..

![scene2](https://user-images.githubusercontent.com/1234848/60690651-d7074c80-9ec0-11e9-8544-7269e6987291.png)

i think the fog should be fixed like this....

![scene_0](https://user-images.githubusercontent.com/1234848/60690656-e1294b00-9ec0-11e9-83a8-8f26dd56cf9c.png)

```x3dv
#X3D V3.3 utf8 Titania V4.5.8

PROFILE Immersive

COMPONENT EnvironmentalEffects:4

DEF Pyramid Transform{
children Shape{
appearance Appearance{
material Material{}
}
geometry IndexedFaceSet{
coordIndex [3,2,1,0,-1,0,1,4,-1,1,2,4,-1,2,3,4,-1,3,0,4,-1]
fogCoord FogCoordinate{
depth [0,0,0,0,2]
}
coord Coordinate{
point [-1 -1 1,1 -1 1,1 -1 -1,-1 -1 -1,0 1 0]
}
}
}
}

Fog{
color 0 0 1
visibilityRange 1
}

Viewpoint{
position -0.00273235 1.57386 0.396757
orientation -0.999984308015103 -0.00441901826013388 -0.00344325444494086 1.32386008516497
}

```

**Comment by create3000** [comment]
FogCoordinate values override the _visibilityRange_ of the Fog, and have therefore an effect whether the viewer is closer or farther. The spec says:

> This node defines a set of explicit fog depths on a per-vertex basis. This depth value shall be applied per-vertex and used to replace the automatically generated depth. Fog coordinates take precedence over implicitly generated depths; **specifying fog coordinates will result in the implicit depth (specified by the visibilityRange field of a node derived from X3DFogObject) being ignored.** (http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/enveffects.html#FogCoordinate)

**Comment by splace** [comment]
> FogCoordinate values override the visibilityRange of the Fog, and have therefore an effect whether the viewer is closer or farther. 

i can certainly now see your interpretation; but, in a single word, i believe it doesn't mean 'override' visibilityRange it means 'bypass' it.

if you read the spec. with the assumption they mean 'bypass' it all makes sense.

if you read the spec. with the assumption they mean 'override', then 'automatically generated depth' and 'implicit depth' are just 'depth' so why didn't they just say that? 

(i think 'automatically generated depth' and 'implicit depth' really mean blending factor.)

notice:
```
FogCoordinate : X3DGeometricPropertyNode {
  MFFloat [in,out] depth    []   [0,1]
  SFNode  [in,out] metadata NULL [X3DMetadataObject]
}
```
the depth field is limited to 0-1, so its can not be a depth to be put INTO one of the formula,(with avatar distance) its has to be the RESULT (and so not dependent on avatar distance), it is simply the blending factor.

**Comment by splace** [comment]
FWIW what you did seems quite useful, having the two different ways would be possible if the fogType field had some more options, but obviously that would have to be in the standard to be reliable.

**Comment by splace** [comment]
[INFO] i posted a comment on x3d-public@web3d.org

**Comment by splace** [comment]
confirmed fixed.

(if anything appears on x3d-public@web3d.org i'll let know)
