### ISSUE TITLE
FIXED_PIPELINE

### ISSUE THREAD

**Issue by naraesk** [create3000/titania#13]
I tried to compile titania on Arch Linux. I resolved all dependencies without any problem. While compiling I recieved ten or twenty times the same error: some attribute or method is defined inside a #ifdef FIXED_PIPELINE macro, and is later used outside an ifdef. Example: 

`Titania/X3D/Browser/Shaders/X3DShadersContext.cpp: In Konstruktor »titania::X3D::X3DShadersContext::X3DShadersContext()«:
Titania/X3D/Browser/Shaders/X3DShadersContext.cpp:81:15: Fehler: »fixedPipeline« wurde in diesem Gültigkeitsbereich nicht definiert
  addChildren (fixedPipeline,
               ^~~~~~~~~~~~~
make[2]: *** [Makefile:4462: Titania/X3D/Browser/Shaders/X3DShadersContext.lo] Fehler 1
make[2]: Verzeichnis „/home/naraesk/workspace/titania2/libtitania-x3d“ wird verlassen
make[1]: *** [Makefile:472: all-recursive] Fehler 1
make[1]: Verzeichnis „/home/naraesk/workspace/titania2“ wird verlassen
make: *** [Makefile:404: all] Fehler 2
`
1. I added all needed #ifdef FIXED_PIPELINE until it compiled completely. However, when I try to open a file I get: "Write to pipe failed."
2. Is it a good idea to compile titania without FIXED_PIPELINE set in the first place? What do I have to do to set it?

**Comment by create3000** [comment]
run ./configure with  --enable-fixed-pipeline

**Comment by create3000** [comment]
don't compile without!

**Comment by naraesk** [comment]
Thanks, this seems to work. However, another error occured:

`Titania/Dialogs/NodeIndex/NodeIndex.cpp: In Elementfunktion »virtual void titania::puck::NodeIndex::initialize()«:
Titania/Dialogs/NodeIndex/NodeIndex.cpp:117:107: Fehler: keine passende Funktion für Aufruf von »Gtk::TreeModelSort::set_sort_func(const Glib::RefPtr<Gtk::TreeViewColumn>&, sigc::bound_mem_functor2<int, titania::puck::NodeIndex, const Gtk::TreeIter&, const Gtk::TreeIter&>)«
  getTreeModelSort () -> set_sort_func (getNameColumn (), sigc::mem_fun (this, &NodeIndex::on_compare_name));
                                                                                                           ^
In file included from /usr/include/gtkmm-3.0/gtkmm/liststore.h:30:0,
                 from /usr/include/gtkmm-3.0/gtkmm.h:202,
                 from Titania/Dialogs/NodeIndex/../../Browser/UserData.h:55,
                 from Titania/Dialogs/NodeIndex/NodeIndex.h:54,
                 from Titania/Dialogs/NodeIndex/NodeIndex.cpp:51:
/usr/include/gtkmm-3.0/gtkmm/treesortable.h:201:8: Anmerkung: candidate: void Gtk::TreeSortable::set_sort_func(const Gtk::TreeModelColumnBase&, const SlotCompare&)
   void set_sort_func(const TreeModelColumnBase& sort_column, const SlotCompare& slot);
        ^~~~~~~~~~~~~
/usr/include/gtkmm-3.0/gtkmm/treesortable.h:201:8: Anmerkung:   keine bekannte Umwandlung für Argument 1 von »const Glib::RefPtr<Gtk::TreeViewColumn>« nach »const Gtk::TreeModelColumnBase&«
/usr/include/gtkmm-3.0/gtkmm/treesortable.h:208:8: Anmerkung: candidate: void Gtk::TreeSortable::set_sort_func(int, const SlotCompare&)
   void set_sort_func(int sort_column_id, const SlotCompare& slot);
        ^~~~~~~~~~~~~
/usr/include/gtkmm-3.0/gtkmm/treesortable.h:208:8: Anmerkung:   keine bekannte Umwandlung für Argument 1 von »const Glib::RefPtr<Gtk::TreeViewColumn>« nach »int«
make[2]: *** [Makefile:2091: Titania/Dialogs/NodeIndex/NodeIndex.o] Fehler 1
make[2]: Verzeichnis „/home/naraesk/workspace/titania2/Titania“ wird verlassen
make[1]: *** [Makefile:472: all-recursive] Fehler 1
make[1]: Verzeichnis „/home/naraesk/workspace/titania2“ wird verlassen
make: *** [Makefile:404: all] Fehler 2`

Any ideas?

Further, cgal is required as dependency, but the configure script does not check if its installed.

**Comment by create3000** [comment]
> > Further, cgal is required as dependency, but the configure script does not check if its installed.

CGAL does not provide a package-config file, ie. I don't know how to check for CGAL.

**Comment by naraesk** [comment]
Thanks for the fix, it compiled now successfully. However, when i try to open a x3d file I get a white scene and the following output:

> Write to pipe failed.
> Couldn't load any URL of
> "file:///home/naraesk/workspace/titania2/Library/Examples/Arcadia/stage/index.x3d"

Btw, I had a look at commit f12f2d1 and it includes several absolute paths ("/home/holger/"). Is it supposed to be like that?

**Comment by create3000** [comment]
Titania must be installed correctly otherwise some components cannot be found.
`Write to pipe failed` occurs when 'titania-x3d2vrml' cannot be found, it is located in the bin folder of your installation directory and this directory must be the search path of bin programs.

**Comment by create3000** [comment]
Additionally to get  'titania-x3d2vrml' work, some perl libraries must be installed too. The list of libraries required can be found in ./debian/control file of the package of Titania.

**Comment by naraesk** [comment]
Thanks again, I made further progress. After adding titania-x3dxvrml to the bin directory and installing 2 perl libs there are no errors anymore.

However, the output is still strange. This is what I get after opening temple.x3d from the examples: 
![screenshot_20161020_215305](https://cloud.githubusercontent.com/assets/7393797/19575672/21a370a4-9710-11e6-9823-8eaf0005504f.png)
When running from console only some gtk warnings about style.css are printed, this should not be important.

**Comment by naraesk** [comment]
Converted a x3d file with titania-x3d2vrml and viewed the result with InstantPlayer and it looked as expected.

**Comment by create3000** [comment]
There is now a `make run` target. Can you try it and let me know if it operates normally.

**Comment by naraesk** [comment]
Thank you very very much, everything seems to work now. :-)
