### ISSUE TITLE
'detach from group' not working for 'layer' and 'layoutlayer' nodes

### ISSUE THREAD

**Issue by splace** [create3000/titania#131]
tested and works for all other grouping nodes

**Comment by create3000** [comment]
Yes, this is the intended behavior. Layer and LayoutLayer node are also no X3DGrouping node, see https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/layering.html#Layer and https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/layout.html#LayoutLayer. The only place where these nodes make sense is as child of a LayerSet node, thus I think it makes no sense to detach them. I think the menu items 'Detach From Group', 'Create Parent Group', and 'Remove Parent' should be removed when hovering these nodes.
