### ISSUE TITLE
trying something from https://github.com/create3000/x_ite

### ISSUE THREAD

**Issue by mufti11** [create3000/titania#133]
When i try frmo https://github.com/create3000/x_ite (github HTML reduces the code)

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8"/>
    <link rel="stylesheet" type="text/css" href="http://code.create3000.de/x_ite/latest/dist/x_ite.css"/>
    <script type="text/javascript" src="http://code.create3000.de/x_ite/latest/dist/x_ite.min.js"></script>
    <style>
    X3DCanvas {
      width: 768px;
      height: 432px;
    }
    </style>
  </head>
  <body>
    <X3DCanvas src="path/to/your/X3D/world.x3d">
      <p>Your browser may not support all features required by X_ITE!</p>
    </X3DCanvas>
  </body>
</html>

Whatever X3D file i use for path/to/your/X3D/world.x3 it fails with "failed loading world".
This works only, if the X3D file is on a webserver, but not local files.

The earlier versions of X_ITE were able to load local X3D files.

**Comment by splace** [comment]
console output could explain it.

(assuming you are meaning x-ite vrml browser, which has its own repo., this is the titania vrml editor.)

**Comment by mufti11** [comment]
There is no console output, if x_ite showa "failrf loading world".

Instead, x_ite shows so HTML with some <div></dev> commands

**Comment by splace** [comment]
i think the problem might be straight-forwardly diagnosed if you post the html. 

>There is no console output, if x_ite showa "failrf loading world".

the console is a feature of the html browser, you have to open it to see whats there, AFAIK you can't get "failed loading world" without at least the loading info. logged in the console.

> x-ite vrml browser, which has its own repo., this is the titania vrml editor

think about moving to x-ite's repo. you will see there other peoples problems and solutions.

**Comment by create3000** [comment]
http://create3000.de/x_ite/getting-started/#embedding-x-ite-within-a-web-page explains how to embed a X3D world into a HTML page. Also have a look at http://create3000.de/x_ite/getting-started/#using-firefox-chrome-and-opera-with-local-files.

**Comment by create3000** [comment]
'Failed loading world' is shown when the file is not found or the browser is unable to load the file. First this means X_ITE is running, and there should be some Console output with additionally explanations of the error. Firefox shows the console if you press Ctrl-Shift-K. A common mistake is caused due to the CORS loading error, which is explained here http://create3000.de/x_ite/getting-started/#using-firefox-chrome-and-opera-with-local-files.

**Comment by create3000** [comment]
**CORS issue explained:**
If you use Firefox there are some rules, how you organize you files and directories, Chrome and Opera are explained in the link above.

**file:// protocol: (Firefox can handle file:// protocol) (not longer supported, see below)**
The HTML file can be in any directory but the X3D files must be in the same directory or in a sub-directory of the directory where the HTML file is located.

**http:// protocol:**
If you put your files on a server, all files HTML and X3D must be under the same domain.

**Comment by create3000** [comment]
https://discourse.mozilla.org/t/a-network-error-occurred-thrown-when-using-xmlhttprequest-on-file-protocol-with-firefox-68/44259
it turns out that Firefox has now the same strict CORS handling as Chrome or Opera. That means that you have to setup a 'localhost' server.
