### ISSUE TITLE
Segmentation fault or memory error on startup

### ISSUE THREAD

**Issue by bcm0** [create3000/titania#136]
**Describe the bug**
Install titania using flatpak or snap. You get segmentation fault or invalid memory reference.

**To Reproduce**
Install latest Arch Linux or Ubuntu 18.10.
Use instructions from here https://github.com/create3000/titania#installation.
Try to start it.

**Expected behavior**
Titania window shows up.

**Additional context**
I already tried compiling titania from source but it failed.
Please let me know what a working setup is.
Do you think appimage could be useful?

**Comment by create3000** [comment]
What graphics card do you use?
What for output comes when you start Titania from the console?

**Comment by bcm0** [comment]
Some onboard intel graphics.
Output with snap:
>  Titania started ...
>  Compiled at Nov 20 2019 07:46:22
> 
> Gtk-Message: Failed to load module "canberra-gtk-module"
> Segmentation fault (core dumped)

With flatpak:
See this paste http://dpaste.com/0BSAYT2

**Comment by create3000** [comment]
Related to https://github.com/create3000/titania/issues/75

**Comment by bcm0** [comment]
So I assume there is no easy fix.

**Comment by create3000** [comment]
This issue is known. Titania only runs if you use an ATI or NVIDIA graphics card.
