### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by naraesk** [create3000/titania#14]
Just a small note, feel free to add it to README or so:

Since it was a bit tricky to compile titania successfully on my system, I created a package for AUR, the arch linux user repository which should simplify the process for other users: https://aur.archlinux.org/packages/titania-git/

**Comment by create3000** [comment]
It's the first time I hear about AUR packages and I would like to make this public. Please, please can you explain what an AUR package is and what's the purpose for.

**Comment by create3000** [comment]
Upated README.md and website at http://titania.create3000.de/download/#c473.

**Comment by naraesk** [comment]
They are specific for Arch Linux. Aur Packages not precompiled, they are more or less simply a script that downloads the source code, installs all dependencies and executes the commands to compile and install the software.

**Comment by create3000** [comment]
Made an announcement on the X3D public mailing list.
http://web3d.org/pipermail/x3d-public_web3d.org/2016-October/005439.html

**Comment by create3000** [comment]
Made and announcement at the landing page with special thanks to you:
http://titania.create3000.de/

**Comment by naraesk** [comment]
Thanks. Btw, the package always builds and installs the latest version from github. Usually you would like to have another package for stable releases. However, there seems to be no sourcecode tarball for version 2.0.1 on github. If you could create it, I'll create the aur package for stable releases.

**Comment by create3000** [comment]
Cool. Thank you for your valuable clue! I have just created the titania-stable project at https://github.com/create3000/titania-stable. And also have a look at the updated download paragraph for Arch Linux http://titania.create3000.de/download/#c473 :).

**Comment by naraesk** [comment]
Oh, I didn't mean to create a second repository. From my point of view a release (https://github.com/create3000/titania/releases) would have been sufficient. ;)

Anyway, I'll create the stable package soon.

**Comment by create3000** [comment]
Ok, this is a good point. I created a new release now at https://github.com/create3000/titania/releases.

**Comment by naraesk** [comment]
Here is the package: https://aur.archlinux.org/packages/titania

It builds titiana based on the tar ball. If you release a new version, the package has to be updated manually. If I should miss a new release, feel free to drop me a note.

greets from leipzig ;)

**Comment by create3000** [comment]
Released a new version today!

**Comment by naraesk** [comment]
Just to make sure: Do I have to run make install or make run or both? INSTALL and README seems to be inconsistent

**Comment by naraesk** [comment]
so? :-)
