### ISSUE TITLE
Edit vertices/edges/faces and Logic

### ISSUE THREAD

**Issue by anonimo82** [create3000/titania#145]
Hello everyone.
I can't get how to alter a geometry, in eg, a box.
That is, move vertices/edges/faces.

Plus, I can't enter anything in the Logic editor, why?
Is it there any hotkey I should know?
Or maybe a specific procedure?

Thanks in advance for any help.

Bye, Ivano.

**Comment by anonimo82** [comment]
@create3000 
Please, help

**Comment by create3000** [comment]
To edit a geometry, select an object, for instance a box, then open the Geometry Editor from the Toolbar, and select the Hammer to smash an primitive node like Box into an IndexedFaceSet. Now you can select the Edit button from the Geometry Editor, the selection will change and shows polygons and vertices.

To start working with the Logic Editor, drag n drop a node from the Outline Editor into the Logic Editor, now you can start connect fields to create routes.

**Comment by anonimo82** [comment]
Nice, I made it to edit vertices and add logic nodes to the logic editor.
Thanks a lot.
