### ISSUE TITLE
Oldest release on Github is labeled "latest"

### ISSUE THREAD

**Issue by david672orford** [create3000/titania#147]
**Describe the bug**
On the Github page the oldest release (4.1.0 from April 2017) is marked as the latest. This creates the impression the project has not made a release in nearly five years.

**To Reproduce**
1. Go to https://github.com/create3000/titania/
2. Look at the middle of the right-hand column and note that the "Latest" release is from April 2017 

**Expected behavior**
Should show that version 4.6.11 from 2 September 2020 is the latest release.

**Comment by create3000** [comment]
Thank you. Now fixed.
