### ISSUE TITLE
Flatpak install uses EOL platforms

### ISSUE THREAD

**Issue by andreasplesch** [create3000/titania#148]
flatpak install raises:

```
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.32 runtime is no longer supported as of 11th March 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 3.32 runtime is no longer supported as of 11th March 2020. Please ask your application developer to migrate to a supported platform.
Info: org.freedesktop.Platform.html5-codecs is end-of-life, with reason: The Freedesktop SDK 18.08 runtime is no longer supported as of 31th August 2020. Please ask your application developer to migrate to a supported platform.
```

Please migrate to supported platform as mentioned.

**Comment by create3000** [comment]
If you are able to use `snap` then there is also a snap package. See https://snapcraft.io/titania.

**Comment by andreasplesch** [comment]
Thanks. The flatpak install still works. It is just a warning at this point. It may be good to mention in the install instructions that it will download and install more than 600MB because of gnome. But the software works then fine on my Debian Buster system.

**Comment by create3000** [comment]
There is now a new flatpak available with runtime version 42. :)

**Comment by andreasplesch** [comment]
I will give it a try.

**Comment by andreasplesch** [comment]
The gnome.Platform updates to version 42 and warnings are removed. Now freedesktop platform v. 1.6 is no longer supported:
![image](https://user-images.githubusercontent.com/6171115/167433934-51bd03c0-257b-4325-ad3a-d0a074990689.png)

**Comment by andreasplesch** [comment]
Trying to run I get now:

```
bwrap: Can't mkdir /app/lib/ffmpeg: Read-only file system
error: ldconfig failed, exit status 256
```

**Comment by andreasplesch** [comment]
I uninstalled all on flatpak, and reinstalled de.create3000.titania. There are no freedesktop.Platform warnings but there is still the error when trying to run:

```
bwrap: Can't mkdir /app/lib/ffmpeg: Read-only file system
error: ldconfig failed, exit status 256
```

**Comment by andreasplesch** [comment]
moved to #151
