### ISSUE TITLE
Cannot edit fields which are defaults.

### ISSUE THREAD

**Issue by andreasplesch** [create3000/titania#149]
Cannot edit fields which are defaults.

**Describe the solution you'd like**
Be able to edit all fields in the tree.

**Describe alternatives you've considered**
Edit x3d in text editor. This is possible but inconvenient.

As an example, opening

https://www.web3d.org/x3d/content/examples/Basic/course/GeometryExampleIndex.html

will only show diffuseColor as a Material field. There does not seem to be a way to change the specularColor which is at the default value.

**Comment by create3000** [comment]
I you expand a node in the Outline Editor, it shows only the changed fields. If you want to show all field hold down the Shift-key and collapse + expand the node again.

**Comment by andreasplesch** [comment]
Super, that works. I added two sentences in the wiki which may help with discovering that feature:

https://github.com/create3000/titania/wiki/Using-the-Outline-Editor

**Comment by create3000** [comment]
Thank you!
