### ISSUE TITLE
Can't compile Polyline2DTool

### ISSUE THREAD

**Issue by naraesk** [create3000/titania#16]
with the current version from git i get the following error message

 ` CXX      Titania/X3D/Tools/Geometry2D/Polyline2DTool.lo
make[2]: *** Keine Regel vorhanden, um das Ziel „Titania/X3D/Tools/Geometry2D/Polypoint2DTool.cpp“, 
  benötigt von „Titania/X3D/Tools/Geometry2D/Polypoint2DTool.lo“, zu erstellen.  Schluss.
make[2]: Verzeichnis „/home/naraesk/workspace/aur/titania-git/src/titania/libtitania-x3d“ wird verlassen
make[1]: *** [Makefile:464: all-recursive] Fehler 1
make[1]: Verzeichnis „/home/naraesk/workspace/aur/titania-git/src/titania“ wird verlassen
make: *** [Makefile:396: all] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...
`

**Comment by rainmanh** [comment]
@naraesk , you should build from the latest release instead:
https://github.com/create3000/titania/releases/

Specifically : https://github.com/create3000/titania/releases/tag/titania-v2.1.0

**Comment by create3000** [comment]
Fix commited: Uploaded missing file.

**Comment by naraesk** [comment]
Such a commit doesn't exist. ;)

**Comment by create3000** [comment]
Fix commited: Uploaded now all files. Verified GitHub project.
