### ISSUE TITLE
ProtoInstance containerField holds field name for XML encoding

### ISSUE THREAD

**Issue by brutzman** [create3000/titania#19]
Incorrect construct for ProtoInstance containerField.  See for example DLMF/21.4.F1a.x3d:

``<Appearance >
    <texture><ProtoInstance name="pixelTexture_modlegend" ></ProtoInstance></texture>
</Appearance>``

should be

``<Appearance >
    <ProtoInstance name="pixelTexture_modlegend" containerField='texture'/>
</Appearance>``

or, using equivalent paired open/close tags,

``<Appearance >
    <ProtoInstance name="pixelTexture_modlegend" containerField='texture'></ProtoInstance>
</Appearance>``

etc.

**Comment by andreasplesch** [comment]
Could you enclose the xml in ```<>``` triple backticks to make those visible, please ? Thanks. Does the fixed example still work in cobweb ? If not, it would be great to file an issue with cobweb as well.

**Comment by andreasplesch** [comment]
Oh, well, from x3d-public:
example DLMF/21.4.F1a.x3d:
```
> <Appearance >
>      <texture><ProtoInstance name="pixelTexture_modlegend" ></ProtoInstance></texture>
> </Appearance>
>
> should be
>
> <Appearance >
>      <ProtoInstance name="pixelTexture_modlegend" containerField='texture'/>
> </Appearance>

**Comment by create3000** [comment]
Recent version of Titania will export valid XML.
