### ISSUE TITLE
Makefile.in files missing

### ISSUE THREAD

**Issue by josiah47** [create3000/titania#2]
./autogen.sh --enable-release --prefix=`/usr/local/`

basically complains about missing Makefile.in in all directories, I copied them manually over from the bazaar repo and then it proceeded to work.

also missing ./po/POTFILES.in

**Comment by create3000** [comment]
Just added and commited.

**Comment by create3000** [comment]
There was a simple warning when running autogen.sh that causes it not to generate Makefile.in's.
