### ISSUE TITLE
Compile error: Gst::XImageSink

### ISSUE THREAD

**Issue by naraesk** [create3000/titania#21]
Can't compile latest git version:

> Titania/X3D/Browser/Sound/MediaStream.cpp: In Elementfunktion »void titania::X3D::MediaStream::setup()«:
Titania/X3D/Browser/Sound/MediaStream.cpp:134:11: Fehler: »class Gst::XImageSink« hat kein Element namens »set_last_sample_enabled«; meinten Sie »set_async_enabled«?
  vsink -> set_last_sample_enabled (true);
           ^~~~~~~~~~~~~~~~~~~~~~~
           set_async_enabled
Titania/X3D/Browser/Sound/MediaStream.cpp: In Elementfunktion »void titania::X3D::MediaStream::on_message(const Glib::RefPtr<Gst::Message>&)«:
Titania/X3D/Browser/Sound/MediaStream.cpp:340:89: Fehler: »class Gst::MessageStateChanged« hat kein Element namens »parse_new_state«
    const auto state = Glib::RefPtr <Gst::MessageStateChanged>::cast_static (message) -> parse_new_state ();
                                                                                         ^~~~~~~~~~~~~~~
Titania/X3D/Browser/Sound/MediaStream.cpp: In Elementfunktion »Gst::PadProbeReturn titania::X3D::MediaStream::on_video_pad_got_buffer(const Glib::RefPtr<Gst::Pad>&, const Gst::PadProbeInfo&)«:
Titania/X3D/Browser/Sound/MediaStream.cpp:454:31: Fehler: »class Gst::XImageSink« hat kein Element namens »get_last_sample«; meinten Sie »get_base_type«?
  const auto sample = vsink -> get_last_sample ();
                               ^~~~~~~~~~~~~~~
                               get_base_type

**Comment by create3000** [comment]
Even the latest version of gstreamermm defines `set_last_sample_enabled`
https://github.com/GNOME/gstreamermm/blob/master/gstreamer/src/basesink.hg#L173

**Comment by create3000** [comment]
Which version of gstreamermm do you compile against?

**Comment by naraesk** [comment]
gstreamermm 1.4.3
