### ISSUE TITLE
"invalid memory reference" when quit, after opening same file twice

### ISSUE THREAD

**Issue by splace** [create3000/titania#23]
~ $ flatpak run de.create3000.titania

*** The browser is requested to replace the world with ''.

*** The browser is requested to replace the world with ''.

Done loading scene 'file:///app/share/titania/tools/library/RoundedRectangle2D.x3dv'.
Done loading image 'file:///app/share/titania/tools/library/gradient.png'.

********************************************************************************
********************************************************************************
Welcome to Titania X3D Browser 4.3.1:
	Compiled at Jul 11 2018 08:59:21
	Current Graphics Renderer
		Name: X.Org AMD Radeon HD 8600 Series (AMD OLAND / DRM 3.25.0 / 4.17.17-87.current, LLVM 5.0.0)
	OpenGL extension version: 3.0 Mesa 17.2.7
	Shading language version: 1.30, 1.0 es X_ITE (default)
	Rendering Properties
		Texture units: 8 / 184
		Max texture size: 16384 × 16384 pixel
		Max lights: 8
		Max clip planes: 6
		Antialiased: false
		Color depth: 32 bits
		Texture memory: 1.0 kB
		Max vertex uniform vectors: 4096
		Max fragment uniform vectors: 4096
		Max vertex attribs: 16
	Current Javascript Engine
		Name: Mozilla Foundation SpiderMonkey
		Description: JavaScript-C 1.8.5 2011-03-31
		Version: ECMAv5
********************************************************************************
********************************************************************************

Done loading scene 'file:///app/share/titania/tools/GridTool.x3dv'.
Done loading scene '/app/share/titania/ui/Logo.x3dv'.
Done loading scene 'file:///app/share/titania/tools/AxonometricGridTool.x3dv'.
Done loading scene 'file:///app/share/titania/tools/AngleGridTool.x3dv'.

********************************************************************************
********************************************************************************
Welcome to Titania X3D Browser 4.3.1:
	Compiled at Jul 11 2018 08:59:21
	Current Graphics Renderer
		Name: X.Org AMD Radeon HD 8600 Series (AMD OLAND / DRM 3.25.0 / 4.17.17-87.current, LLVM 5.0.0)
	OpenGL extension version: 3.0 Mesa 17.2.7
	Shading language version: 1.30, 1.0 es X_ITE (default)
	Rendering Properties
		Texture units: 8 / 184
		Max texture size: 16384 × 16384 pixel
		Max lights: 8
		Max clip planes: 6
		Antialiased: false
		Color depth: 32 bits
		Texture memory: 1.0 kB
		Max vertex uniform vectors: 4096
		Max fragment uniform vectors: 4096
		Max vertex attribs: 16
	Current Javascript Engine
		Name: Mozilla Foundation SpiderMonkey
		Description: JavaScript-C 1.8.5 2011-03-31
		Version: ECMAv5
********************************************************************************
********************************************************************************

Done loading scene 'file:///app/share/titania/pages/about/splash.x3dv'.
Done loading scene '/app/share/titania/pages/about/library/Colors.x3dv#Red'.
Done loading scene 'file:///app/share/titania/tools/library/ToolShader.x3dv'.
Done loading scene 'file:///app/share/titania/tools/library/ToolShader.x3dv'.
Done loading scene 'file:///app/share/titania/tools/library/ToolShader.x3dv'.
Done loading scene 'file:///app/share/titania/tools/library/AngleGrid.x3dv#AngleGrid'.
Done loading scene 'file:///app/share/titania/tools/library/Grid.x3dv#Grid'.
Done loading scene 'file:///app/share/titania/tools/library/AxonometricGrid.x3dv#AxonometricGrid'.

*** The browser is requested to replace the world with 'file:///app/share/titania/pages/about/splash.x3dv'.

*** The browser is requested to replace the world with '/app/share/titania/ui/Logo.x3dv'.

Done loading scene 'file:///app/share/titania/tools/library/RoundedRectangle2D.x3dv'.
Done loading image 'file:///app/share/titania/tools/library/gradient.png'.
Done loading scene 'file:///home/simon/Desktop/chess.wrl'.
Done loading scene 'file:///app/share/titania/tools/library/RoundedRectangle2D.x3dv'.
Done loading image 'file:///app/share/titania/tools/library/gradient.png'.

*** The browser is requested to replace the world with 'file:///home/simon/Desktop/chess.wrl'.

*** The browser is requested to replace the world with ''.

Done loading scene 'file:///app/share/titania/tools/library/RoundedRectangle2D.x3dv'.

********************************************************************************
********************************************************************************
Welcome to Titania X3D Browser 4.3.1:
	Compiled at Jul 11 2018 08:59:21
	Current Graphics Renderer
		Name: X.Org AMD Radeon HD 8600 Series (AMD OLAND / DRM 3.25.0 / 4.17.17-87.current, LLVM 5.0.0)
	OpenGL extension version: 3.0 Mesa 17.2.7
	Shading language version: 1.30, 1.0 es X_ITE (default)
	Rendering Properties
		Texture units: 8 / 184
		Max texture size: 16384 × 16384 pixel
		Max lights: 8
		Max clip planes: 6
		Antialiased: false
		Color depth: 32 bits
		Texture memory: 1.0 kB
		Max vertex uniform vectors: 4096
		Max fragment uniform vectors: 4096
		Max vertex attribs: 16
	Current Javascript Engine
		Name: Mozilla Foundation SpiderMonkey
		Description: JavaScript-C 1.8.5 2011-03-31
		Version: ECMAv5
********************************************************************************
********************************************************************************

Done loading image 'file:///app/share/titania/tools/library/gradient.png'.
Done loading scene 'file:///app/share/titania/pages/about/splash.x3dv'.

*** The browser is requested to replace the world with 'file:///app/share/titania/pages/about/splash.x3dv'.

Done loading image 'file:///app/share/titania/tools/library/gradient.png'.
Done loading scene 'file:///app/share/titania/tools/library/RoundedRectangle2D.x3dv'.
Done loading scene 'file:///app/share/titania/pages/about/tab.x3dv'.
Done loading scene 'file:///app/share/titania/pages/about/library/Rotor.x3dv'.

*** The browser is requested to replace the world with 'file:///app/share/titania/pages/about/tab.x3dv'.

Bad Image: Magick: zero-length blob not permitted `' @ error/blob.c/BlobToImage/341, in URL 'data:'.
Bad Image: Magick: zero-length blob not permitted `' @ error/blob.c/BlobToImage/341, in URL 'data:'.
Bad Image: Magick: zero-length blob not permitted `' @ error/blob.c/BlobToImage/341, in URL 'data:'.
Done loading image 'file:///app/share/titania/pages/about/tab.x3dv'.
Done loading image 'file:///app/share/titania/pages/about/tab.x3dv'.
Done loading image 'file:///app/share/titania/pages/about/tab.x3dv'.
Done loading image 'file:///app/share/titania/pages/about/tab.x3dv'.
Done loading image 'file:///app/share/titania/pages/about/tab.x3dv'.
Done loading image 'file:///app/share/titania/pages/about/tab.x3dv'.
Done loading scene 'file:///home/simon/Desktop/chess.wrl'.

*** The browser is requested to replace the world with 'file:///home/simon/Desktop/chess.wrl'.

(titania:3): Gtk-CRITICAL **: _gtk_accel_group_attach: assertion 'g_slist_find (accel_group->priv->acceleratables, object) == NULL' failed

*** The browser is requested to replace the world with ''.

Done loading scene 'file:///app/share/titania/tools/library/RoundedRectangle2D.x3dv'.

********************************************************************************
********************************************************************************
Welcome to Titania X3D Browser 4.3.1:
	Compiled at Jul 11 2018 08:59:21
	Current Graphics Renderer
		Name: X.Org AMD Radeon HD 8600 Series (AMD OLAND / DRM 3.25.0 / 4.17.17-87.current, LLVM 5.0.0)
	OpenGL extension version: 3.0 Mesa 17.2.7
	Shading language version: 1.30, 1.0 es X_ITE (default)
	Rendering Properties
		Texture units: 8 / 184
		Max texture size: 16384 × 16384 pixel
		Max lights: 8
		Max clip planes: 6
		Antialiased: false
		Color depth: 32 bits
		Texture memory: 1.0 kB
		Max vertex uniform vectors: 4096
		Max fragment uniform vectors: 4096
		Max vertex attribs: 16
	Current Javascript Engine
		Name: Mozilla Foundation SpiderMonkey
		Description: JavaScript-C 1.8.5 2011-03-31
		Version: ECMAv5
********************************************************************************
********************************************************************************

Done loading image 'file:///app/share/titania/tools/library/gradient.png'.
Done loading scene 'file:///app/share/titania/pages/about/splash.x3dv'.

*** The browser is requested to replace the world with 'file:///app/share/titania/pages/about/splash.x3dv'.

Done loading image 'file:///app/share/titania/tools/library/gradient.png'.
Done loading scene 'file:///app/share/titania/tools/library/RoundedRectangle2D.x3dv'.
Done loading scene 'file:///app/share/titania/pages/about/tab.x3dv'.
Done loading scene 'file:///app/share/titania/pages/about/library/Rotor.x3dv'.

*** The browser is requested to replace the world with 'file:///app/share/titania/pages/about/tab.x3dv'.

Bad Image: Magick: zero-length blob not permitted `' @ error/blob.c/BlobToImage/341, in URL 'data:'.
Bad Image: Magick: zero-length blob not permitted `' @ error/blob.c/BlobToImage/341, in URL 'data:'.
Bad Image: Magick: zero-length blob not permitted `' @ error/blob.c/BlobToImage/341, in URL 'data:'.
Done loading image 'file:///app/share/titania/pages/about/tab.x3dv'.
Done loading image 'file:///app/share/titania/pages/about/tab.x3dv'.
Done loading image 'file:///app/share/titania/pages/about/tab.x3dv'.
Done loading image 'file:///app/share/titania/pages/about/tab.x3dv'.
Done loading image 'file:///app/share/titania/pages/about/tab.x3dv'.
Done loading image 'file:///app/share/titania/pages/about/tab.x3dv'.
################################################################################
#
# Backtrace
#
# Error: signal 11 SIGSEGV
#
# Invalid memory reference
#
################################################################################
/app/lib/libtitania-standard.so.0(_ZN7titania17backtrace_symbolsB5cxx11Em+0x2b) [0x7f4c3005f70b]
/app/lib/libtitania-standard.so.0(+0x110d2f) [0x7f4c3005fd2f]
/app/lib/libtitania-standard.so.0(+0x111406) [0x7f4c30060406]
/lib/libc.so.6() [0x3153a330b0]
/lib/libstdc++.so.6(_ZSt28_Rb_tree_rebalance_for_erasePSt18_Rb_tree_node_baseRS_+0x2a0) [0x7f4c2fa3d530]
/app/lib/libtitania-x3d.so.0(_ZNK7titania3X3D9X3DOutput13eraseInterestEPKvS3_+0xff) [0x7f4c31ed2aff]
/app/lib/libtitania-x3d.so.0(_ZNK7titania3X3D9X3DOutput16processInterestsEv+0xbd) [0x7f4c31ed1f8d]
/app/lib/libtitania-x3d.so.0(_ZN7titania3X3D8X3DInput5clearEv+0xd) [0x7f4c31ed001d]
/app/lib/libtitania-x3d.so.0(_ZN7titania3X3D9X3DObject7disposeEv+0x23) [0x7f4c31ed00f3]
/app/lib/libtitania-x3d.so.0(_ZN7titania3X3D15X3DParentObject7disposeEv+0x14) [0x7f4c31ed39f4]
titania(_ZN7titania4puck18X3DBrowserNotebook7disposeEv+0xdc) [0x8856ec]
titania(_ZN7titania4puck13BrowserWindowD1Ev+0x3c) [0x83382c]
titania(_ZN7titania4puck13BrowserWindowD0Ev+0x9) [0x8338e9]
titania(_ZN7titania4puck21X3DBrowserApplicationD2Ev+0xb6) [0x7bd996]
titania(_ZN7titania4puck18BrowserApplicationD1Ev+0x5d) [0x7bcdad]
titania(_ZN7titania4puck18BrowserApplication4mainEiPPc+0x39) [0x78d299]
titania(main+0x19d) [0x78dabd]
/lib/libc.so.6(__libc_start_main+0xf1) [0x3153a20291]
titania(_start+0x2a) [0x7bcc7a]

**Comment by create3000** [comment]
Thanks for the detailed response but please can you describe the exact steps to reproduce this issue?

**Comment by splace** [comment]
i opened the same file twice, the second time using recent, then quit.

**Comment by create3000** [comment]
Updated flatpak.

**Comment by splace** [comment]
no longer crashes
