### ISSUE TITLE
feature request/usability bug collection

### ISSUE THREAD

**Issue by splace** [create3000/titania#25]
# show recent files from user not just flatpak sandbox.

open file dialog/recent doesn't show users recent files, only files accessed by the app itself (making it the same as open recent..), obviously when using, say, a text editor in conjunction with Titania this is inconvenient and surprising.

**Comment by splace** [comment]
# single click select in tree view

double clicking is usually for some change

**Comment by splace** [comment]
# reload changed file dialog, all options greyed-out

they still work however.

**Comment by create3000** [comment]
Titania uses Gtk for all widgets and the File Open Dialog is part of that. Please feel free reporting bug regarding to Gtk at https://www.gtk.org/development.php.

**Comment by create3000** [comment]
Or it could be a bug of https://github.com/flatpak/flatpak

**Comment by splace** [comment]
>  Or it could be a bug of https://github.com/flatpak/flatpak

i've had this a couple of times recently, (seems to be happening more) where in the software stack does an end-user report a problem, how would they know? 

Titania / GTK / flatpak / budgie / Solus / Gnome / debian / kernel

i guess i could eliminate flatpak with a repo. install, and Bubgie/Solus with Gnome in a VM, but honestly who has the time for all that.

> Titania uses Gtk for all widgets and the File Open Dialog is part of that. Please feel free reporting bug regarding to Gtk at https://www.gtk.org/development.php.

i do feel that you are the one to do that, after you determine it valid/not and its not something you did, i'm not really in the position to be able.

**Comment by splace** [comment]
note.

probably a mistake, but i added several issues, (intending to add more.) here, rather than as separate ones, basically because i thought it made sense to group small UI issues, they don't seem to me to all be gtk/flatpak upstream problems.

**Comment by create3000** [comment]
> single click select in tree view

If single click is enabled to select in Outline Editor, then it is easy to release the selection or wrongly select something. With double click the selection is more stable and it is harder to make mistakes. **(won't fix)**

**Comment by create3000** [comment]
Please report every single issue in a new one.
