### ISSUE TITLE
Was: cobweb #43

### ISSUE THREAD

**Issue by andreasplesch** [create3000/titania#26]
https://github.com/create3000/cobweb/issues/43

copied here due to titania crash.

test3.wrl:

```
#VRML V2.0 utf8


DEF	integerPosition Script {
    eventIn	SFVec3f	realPosition
    eventOut SFVec3f	realPositionOut
    url	"javascript: 
	function realPosition(value, timestamp) { 
			realPositionOut=value;
                        Browser.print(timestamp);
		}
	"}

Group {
	children[
		DEF sensor ProximitySensor{size 100 100 100}
	]
	ROUTE sensor.position_changed TO integerPosition.realPosition
	ROUTE integerPosition.realPositionOut TO integerPosition.realPosition
}
```
I added the timestamp logging.
freewrl 4.0 crashes also.

**Comment by create3000** [comment]
Fixed event loop breaking when script is involved. 
https://github.com/create3000/titania/commit/46b0b1424a5facd9022ba97ade2cec3d399365bb

**Comment by create3000** [comment]
Fixed fatal bug when executing test2.wrl
https://github.com/create3000/titania/commit/b877a2b61ef7ea435b55a42b320357ec739ad51a
Updated flatpak
