### ISSUE TITLE
titania not respecting, and altering, nautilus setting for "sort folder first".

### ISSUE THREAD

**Issue by splace** [create3000/titania#31]
after using the flatpak and opening a file (using the file open dialog) which displays folders not sorted first, i find my system settings have been changed for nautilus (and all file dialogs) to also not sort folders first.

**Comment by create3000** [comment]
Titania uses Gtk for all widgets and the File Open Dialog is part of that. Please feel free reporting bug regarding to Gtk at https://www.gtk.org/development.php.

**Comment by create3000** [comment]
Have a look at https://gexperts.com/wp/gnome-3-12-filesnautilus-sort-folders-before-files-issues/

**Comment by create3000** [comment]
and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=869904

**Comment by splace** [comment]
there's a lot of noise out there on 'sort folders first', but this looks particularly fishy.... 

nautilus: Major changes in 3.23.90: (feb 2017)
* Syncronize gtk+ and Nautilus setting for sorting the folder first (Felipe Borges)

as a guess:- the gtk+ files dialog needs to be reading the current state, ideally it would be built-in to the dialog, but if it doesn't do it automatically or is unable/broken then nautilus will be set to whatever the gtk+ dialog defaults too. (it happens when you leave the dialog.)

**Comment by create3000** [comment]
https://gitlab.gnome.org/GNOME/gtk/issues/1353

**Comment by splace** [comment]
reported upstream

**Comment by create3000** [comment]
https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html
and
https://developer.gnome.org/gtkmm/3.91/classGtk_1_1FileChooserNative.html

**Comment by splace** [comment]
in-case this helps someone;

>  flatpak run de.create3000.titania;gsettings set org.gtk.Settings.FileChooser sort-directories-first true

reverts to dirs-first when quit.

**Comment by splace** [comment]
fixed by update to gnome 3.3 base #92

**Comment by create3000** [comment]
Reopened again, as it is not fixed.

**Comment by splace** [comment]
yes, i tried to reopen, seems strange but as OP i don't seem to have the rights! i guess i will have to generally hold off on closing issues.(this really seems like a poor design on github.)

i did test and was sure it was not changing the setting, it may be that the flatpak is isolated until after a reboot?

**Comment by create3000** [comment]
I have detected the issue again when using the File Save Dialog.

**Comment by splace** [comment]
For me has gone, i tried several times and either way.

FYI this is the first version of Titania i have download ed from flathub. ( 4.5.3)

BTW it seems i CAN reopen, so closing.
