### ISSUE TITLE
viewpoint animation not working.

### ISSUE THREAD

**Issue by splace** [create3000/titania#33]
i notice, after a bit of investigation, that the definition of the 'jump' parameter in the viewpoint node has changed from vrml to x3d.

sorry for you having to put up with this kind of problematic thing for the standard writers to have done, keeping the SAME name for a DIFFERENT behaviour!!

anyway for vrml 2.0, jump means either animate or not.

````
The jump field specifies whether the user’s view ‘jumps’ (or animates) to the position and orientation of
a bound Viewpoint.
````

for x3d it means jump or don't move.

````
The jump field specifies whether the user's view "jumps" to the position and orientation of a bound Viewpoint node or remains unchanged.
````
anyway titaniz follows the x3d behaviour for vrml worlds, breaking very many.

there is unfortunately extensive examples/documentation using the old vrml 2 meaning for jump.

even here,

> http://www.web3d.org/x3d/content/examples/Basic/development/TestViewpointJumpIndex.html

**Comment by splace** [comment]
i now find the vrml 2 spec on the web3d website using the new definition?

with many other sites having it, vrml 2, with the older definition.

did they, at some point, change the definition without updating the version?  please let it not be so.

**Comment by create3000** [comment]
As far as I know in old VRML players the viewpoint jumps to the new position if the _jump_ field is TRUE when the viewpoint is bound by sending an TRUE event to the _set_bind_ field. If one has clicked an Anchor node with viewpoint link the viewpoint animates to its position. In X3D the behaviour can be controlled by NavigationInfo _transitionType_ field.

If the _jump_ field is FALSE the viewpoint remains at the current position.

That would mean that Titania and X_ITE misses support for VRML behaviour of Viepoint _jump_ field.

**Comment by splace** [comment]
after some reading, i'm fairly sure that you can get the old behaviour like this; 

if viewpoint.jump was FALSE , just remove it and have a navigationInfo, whose default values give you animation.

if viewpoint.jump was TRUE (or unset), then set navigationinfo.transitionType = "TELEPORT"

with a mixture of old jump values, true and false, it gets complex, you would now need two navigationInfo nodes and bind them as required.

**Comment by splace** [comment]
> If one has clicked an Anchor node with viewpoint link the viewpoint animates to its position. 
> If the jump field is FALSE the viewpoint remains at the current position.

when jump=FALSE any bind did animation, this is the main issue.

>  That would mean that Titania and X_ITE misses support for VRML behaviour of Viepoint jump field.

i think you might be OK, this behaviour, although very widespread, seems only to be the long lived "working draft" of 2.0, not the finished standard, so you would be correct to the standard, its just old documentation and world's wouldn't work.  this should have been left to 3 to be changed like this, its a huge waste of all that old resource.

**Comment by splace** [comment]
also...

with the new way to do it, what happens, when you don't have a navigationInfo node, do you animate or teleport? i can't seem to find an answer in the current spec., maybe its browsers choice, which would work i think. if you don't specify you are saying it doesn't matter.

**Comment by create3000** [comment]
If no NavigationInfo is specified, the default values of a NavigationInfo node are used.

I dissagree with you, in CosmoPlayer (the leading VRML viewer) if the _jump_ field was FALSE the viewpoint remains at its current position.

**Comment by create3000** [comment]
[elevator.zip](https://github.com/create3000/titania/files/2364426/elevator.zip)

There is an old elevator test file (not of mine) that shows the behavior if _jump_ is FALSE. (zoom or scroll to move to the elevator and back)

**Comment by splace** [comment]
interestingly there is a comment in that example... 

````
http://www.web3d.org/x3d/content/examples/Basic/development/TestViewpointJumpIndex.html
````

...to the effect that Cosmo is broken.

But i now agree with you, Cosmo might have been the only one that was sort of right, right to the new definition, wrong the origin working draft.

Cosmo was a bit special, (it had the most following on Apple and was the only option there, so people on apple didn't see the x-browser problems, it was not well supported on windows/linux. direct3d vs opengl?), it behaved somewhat as the spec., the spec was changed to say what Cosmo WAS actually doing, because it was written by the same guys writing the spec., unfortunately several times the spec. was badly written, and everyone else followed the wording of the spec.  This now makes sense of why the spec. changed, without a version change, it was because the writers regarded it as clarification, unfortunately by the time it happened, the damage was already done.

i tested in blaxxun, Cortona, freeview, and some others, Cosmo was usually the outlier.

**Comment by splace** [comment]
i notice the example;

> http://www.web3d.org/x3d/content/examples/Basic/development/TestViewpointJumpIndex.html

works completely differently in X3DOM.

i woulld guess it works as intended in Blaxxun, Cortona....

**Comment by splace** [comment]
>  There is an old elevator test file (not of mine) that shows the behavior if jump is FALSE. (zoom or scroll to move to the elevator and back)

i think that example was intended to allow you to animate to the next viewpoint, page down, triggering the lift. you could walk etc. to do it also, but in that case viewpoints wouldn't be needed, the viewpoints are, as they usually were, a quick way to move though the important sites in a world.

this appears to be an example of what i'm talking about, its now broken, from its original design.

**Comment by splace** [comment]
i changed the elevator example using the above conversion rules.

but, Titania and x_ite don't seem to support viewpoints inside a transfrom.

````
#VRML V2.0 utf8

NavigationInfo{}

DirectionalLight { }
Transform {
  translation 10 10 10
  children [
    DEF StartViewpoint Viewpoint {
     description "StartViewpoint"
    }
    Transform {
      translation 0 0 -3.5
      children Shape {
        appearance Appearance {
          material Material {
            diffuseColor 0 1 0
          }
        }
        geometry Cone { }
      }
    }
    Transform {
      translation 0 4 -3.5
      children Shape {
        appearance Appearance {
          material Material {
            diffuseColor 1 0 0
          }
        }
        geometry Cone { }
      }
    }
    Transform {
      translation 0 8 -3.5
      children Shape {
        appearance Appearance {
          material Material {
            diffuseColor 0 0 1
          }
        }
        geometry Cone { }
      }
    }
    Group {
      children DEF ETransform Transform {
        children [
          DEF EViewpoint Viewpoint {
            description "EViewpoint"
          }
          DEF EProximity ProximitySensor {
            size 2 5 5
          }
          Transform {
            translation 0 -1 0
            children Shape {
              appearance Appearance {
                material Material { }
              }
              geometry Box {
                size 2 0.2 5
              }
            }
          }
        ]
      }
    }
    DEF ElevatorPI PositionInterpolator {
      key [ 0, 1 ]
      keyValue [ 0 0 0, 0 8 0 ]
    }
    DEF TS TimeSensor {
      cycleInterval 10
    }
    DEF JumpViewpoint Viewpoint {
      description "JumpViewpoint"
    }
  ]
}

ROUTE EProximity.enterTime TO TS.startTime
ROUTE TS.isActive TO EViewpoint.set_bind
ROUTE TS.fraction_changed TO ElevatorPI.set_fraction
ROUTE ElevatorPI.value_changed TO ETransform.set_translation
````

**Comment by splace** [comment]
i'm happy to close, not your issue that there is loads of old broken resources.

but maybe it would be useful to have a comment in the docs to explain whats going on.

**Comment by create3000** [comment]
Titania and X_ITE support Viewpoint nodes inside Transform nodes, even if these are animated, but they must have the right values in the _position_ and _orientation_ field.

**Comment by create3000** [comment]
One purpose to set the jump _field_ to FALSE is to create an elevator or shuttle bus. You have two viewpoint one outside the bus and one inside the bus:

* Viewpoint Outside 
* Transform Shuttle
  * Viewpoint ShuttleViewpoint
  * Shape ShuttleShape
  * ProximitiySensor

At the begining the Viewer is bound to the Viewpoint outside. Both Viewpoints have the _jump_ field set to FALSE. The Shuttle is animated to move to a destination and back, and it waits at a stop. If the shuttle is at the stop you can go into the shuttle. The ProximitySensor usually the size of the Shuttle triggers a Viewpoint _set_bind_ and the Viewer is bound to the Viewpoint inside the Shuttle, since the _jump_ field is FALSE you will not recognize the change. Now the Shuttle Transform can be animated. If the Shuttle comes to the next stop the Viewer can go outside the Shuttle and when he leaves the Shuttle the ProximitySensor triggers a set_bind to the Viewpoint outside, since the _jump_ field is FALSE you will not recognize the change.

This was in VRML the case and thus in X3D.

**Comment by create3000** [comment]
Maybe you could rename your old .wrl files to the new format .x3dv and control the behavior with NavigationInfo.transitionType. I must confess Titania is more designed to be an X3D editor than it can VRML.

**Comment by create3000** [comment]
Fixed the case that jump is TRUE, that if a set_bind TRUE event is received by the Viewpoint node, the position is immediately changed, but if an Anchor node is clicked or PgUp/Down the viewpoint is animated if the file was VRML.

**Comment by splace** [comment]
> Fixed the case that jump is TRUE, that if a set_bind TRUE event is received by the Viewpoint node, the position is immediately changed, but if an Anchor node is clicked or PgUp/Down the viewpoint is animated if the file was VRML.

my reading of the spec. is that, without a NavigationInfo node, the browsers can do what it prefers, but if there is one then either of these two ways should do what that indicates. (the currently bound NavigationInfo if more than one) the difference is that jump is always TRUE for Anchors.

**Comment by splace** [comment]
>  This was in VRML the case and thus in X3D.

i agree, and a useful way to do it.

the problem is that the 'working draft' didn't say this for a long time, so as a consequence, a lot of browsers, documentation and worlds were built differently, someone searching the web is presented with all this broken resource. 

since broken viewpoints need not be immediately obvious, like visible content might be, this issue has just remained undiminished over the years.

at the moment, Titania/X-Ite/Cosmo, Blaxxun/Cortona/others, X3DOM and probably even more, are all doing it differently, what chance does a content developer have when using viewpoints?

**Comment by splace** [comment]
> but, Titania and x_ite don't seem to support viewpoints inside a transfrom.

sorry, my mistake, i now see the elevator example has three viewpoints, all with jump=FALSE, so initially pressing pgup/dgdn moves between these three viewpoints, without any visual effect, bit confusing. 

i can see how one is for being on the animated elevator platform, one for being off it, but the others purpose eludes me.

however, if the browser effectively used the anchor method of navigation, so always forced jump=TRUE for keyboard nav. then this might work more intuitively, maybe that what the authors browser did? 

also, surprised this didn't specify "walk" mode, maybe the authors browser had walk as default, and they didn't realise it was a browsers choice, but just guessing here.

**Comment by splace** [comment]
closing because this is really just a conversation now.
