### ISSUE TITLE
ROUTES not working, might be to do with their placement in the file?

### ISSUE THREAD

**Issue by splace** [create3000/titania#34]
cut from broken content and confirmed working in other browsers

````
#VRML V2.0 utf8

DEF	viewer Transform {translation 0 0 5 children [Transform {translation 0 5 0 children [
	DEF flyView Viewpoint {description "Fly Round" position	0 0 20  }
	DEF viewtimer TimeSensor {cycleInterval	10 enabled FALSE loop TRUE}
	DEF	viewrotation OrientationInterpolator {key [0, .3,.7,1] keyValue [0 1 0 0,-0.2 1 0 1.9,0.2 1 0 4.4,0 1 0 6.28]}
]
	ROUTE viewtimer.fraction_changed TO viewrotation.set_fraction
	ROUTE viewrotation.value_changed TO	viewer.rotation
	ROUTE flyView.bindTime TO viewtimer.startTime
	ROUTE flyView.isBound TO viewtimer.enabled
}]}

Shape{
	geometry Box{}
}
````

**Comment by create3000** [comment]
Cannot reproduce this bug. Be aware to be in live mode (to have the Play/Pause Button toggle on) to keep the world running.

**Comment by splace** [comment]
sorry yes, i guess i had it paused. 

i now see titania remembers paused state through a restart, didn't expect that.

i notice the recent files world, always comes up playing, despite the startup state of play/pause button, making it look like things are not paused, but it can actually be paused, so it can come up playing even if Titania is shown as paused.

**Comment by splace** [comment]
titania doesn't remember primitive quality setting, didn't expect that.

**Comment by splace** [comment]
moving to #36
