### ISSUE TITLE
select viewpoint for rendering, UI broken

### ISSUE THREAD

**Issue by splace** [create3000/titania#35]
initially thought non-functional, but discovered that double clicking the viewpoint BELOW the one you want, gets it selected.

also

feature request: specify duration in seconds, rather than frames.

also

time format is currently  "hh:mm:ss:ms", really needs a point not a colon, ie "hh:mm:ss.ms"

**Comment by splace** [comment]
also

feature request: have render settings saved

(update)  i now see this data, and much else besides, is saved in the files Worldinfo node, so it nicely follows the file. however you need to save the file for this to work and i am editing the file in a text editor, not using Titania for editing and so not saving. (this also explains why Titania says a file has been edited, when all you do is use the renderer.)

can i always just delete the Worldinfo, only losing settings, not content?

**Comment by create3000** [comment]
the time format is hh:mm:ss:ff, where ff is the frame

**Comment by splace** [comment]
>  the time format is hh:mm:ss:ff, where ff is the frame

that makes sense; avoids approx. fractions.

seems like a common format i hadn't noticed before, but might be sub-optimal if variable frame rate catches on.

**Comment by splace** [comment]
confirmed fixed
