### ISSUE TITLE
not remembering primitive quality setting

### ISSUE THREAD

**Issue by splace** [create3000/titania#36]

**Comment by create3000** [comment]
Primitive quality must be programatically set in a Script node if you want it permanent.

```
Script {
  url "
function initialize ()
{
  Browser .setBrowserOption ('PrimitiveQuality', 'High');
}
"
}
```

http://create3000.de/users-guide/ecmascript-object-and-function-definitions/browser-services/

**Comment by create3000** [comment]
This should be cross browser compatible.

**Comment by splace** [comment]
i was just looking to build using high quality in Titania, without having to turn it on every startup.

**Comment by splace** [comment]
confirmed working
