### ISSUE TITLE
external tools: python module not found

### ISSUE THREAD

**Issue by splace** [create3000/titania#37]
basic example of dbus usage from manual gives this...

````  
traceback (most recent call last):
  File "****/.config/Titania/Tools/G9Z1OZ.txt", line 3, in <module>
    import gi
ImportError: No module named gi
````

but 

```` 
~ $ python
Python 2.7.15 (default, May  3 2018, 19:05:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>>
````

**Comment by create3000** [comment]
Run `pip install PyGObject` in a terminal. This will install the gi module in your home directory which is accessible from within the flatpak. Pip modules can be found at https://pypi.org/. See also https://en.wikipedia.org/wiki/Pip_(package_manager).

**Comment by create3000** [comment]
if you use python3, use pip3

**Comment by splace** [comment]
thanks, i was hoping to use flatpaks as a way to keep the underlying system untouched, so that deleting them would return me to a base system and moving them to other systems was trivial.

this is a bit unreasonable for external tool dependencies, i was just testing, so will leave it.
