### ISSUE TITLE
[feature request] allow shadings other than gouraud for rendering.

### ISSUE THREAD

**Issue by splace** [create3000/titania#38]
rendering always uses gouraud shading not the current selection.

**Comment by create3000** [comment]
See Browser.setBrowserOption http://create3000.de/users-guide/ecmascript-object-and-function-definitions/browser-services/

**Comment by splace** [comment]
i think you misunderstand, i was using 'rendering' to mean the recording of a movie.

**Comment by create3000** [comment]
https://github.com/create3000/titania/issues/39

**Comment by create3000** [comment]
Preview:

![bildschirmfoto von 2018-09-23 03-46-35](https://user-images.githubusercontent.com/2930196/45923312-7388d100-bee3-11e8-9645-55f0a43c27f7.png)

**Comment by create3000** [comment]
updated flatpak
