### ISSUE TITLE
selecting flat shading results in gouraud shading

### ISSUE THREAD

**Issue by splace** [create3000/titania#39]

**Comment by create3000** [comment]
Duplicate of #38

**Comment by splace** [comment]
>  marked this as a duplicate of #38 2 hours ago

this is in the normal 'main view', #38 was for 'movie' rendering

![screenshot from 2018-09-23 01-22-39](https://user-images.githubusercontent.com/1234848/45922875-7bd71100-becf-11e8-979e-48a1baa78394.png)

**Comment by create3000** [comment]
updated flatpak

**Comment by splace** [comment]
confirmed fixed
