### ISSUE TITLE
unimplemented: Graphite loop optimizations cannot be used

### ISSUE THREAD

**Issue by josiah47** [create3000/titania#4]
since last to pulls, I have git cleaned, git reset and git pull and then ./autogen and then make with the following error, file looks the same as bazaars, must be something else that was just committed, cause I built successfully before the last 2 commits.

Titania/Chrono/ClockBase.cpp:1:0: sorry, unimplemented: Graphite loop optimizations cannot be used (-fgraphite, -fgraphite-identity, -floop-block, -floop-interchange, -floop-strip-mine, -floop-parallelize-all, and -ftree-loop-linear)
 /\* -_\- Mode: C++; coding: utf-8; tab-width: 3; indent-tabs-mode: tab; c-basic-offset: 3 -_-
 ^

**Comment by create3000** [comment]
The latest commit builds fine on Launchpad. Can try another compile?

**Comment by josiah47** [comment]
I did a git pull and then tried again, please see attached for errors.

**Comment by create3000** [comment]
Can't see any attachements.

**Comment by josiah47** [comment]
http://pastebin.com/qfnwAsAJ

sorry didn't notice GIthub give me flack 'Unfortunately, we don't support that file type. Try again with a PNG, GIF, or JPG. Unfortunately, we don't support that file type. Try again with a PNG, GIF, or JPG. '

**Comment by create3000** [comment]
You used »./autogen.sh --enable-release --prefix=`/usr`«, when you comiled first you must not have added --enable-release. I modified configure.ac, so now you can use and please use --enable-release.

**Comment by create3000** [comment]
The second reason for this message is: using the Graphite transformations (parallelization feature) off gcc require configuring and building gcc with the optional cloog and PPL libraries.

**Comment by josiah47** [comment]
http://pastebin.com/zWCfvX4D

seems you introduced a bug

**Comment by create3000** [comment]
Fixed that

**Comment by josiah47** [comment]
I seen a --enable-parallel for the configure, do you suggest doing this?

I am rebuilding gcc with graphite on.

**Comment by create3000** [comment]
If you have (you have) more than one processor then I can recommend this feature. For normal use you can ignore it, if you deal with large polygonal objects you should better turn it on.

**Comment by josiah47** [comment]
I got 8 of them so mine as well use them. gcc with graphite compiled and it is current making, no errors so far.

I did spot a potential error in configure.ac line 50 

```
    [Use 'PARALLE' Configuration [default=NO]]),
```

don't know if its supposed to be PARALLEL or not.

**Comment by josiah47** [comment]
Error:
http://pastebin.com/mRWzJNKm

**Comment by create3000** [comment]
The reason could be that Ubuntu uses gcc version 4.9.1 and this version is at least required ...

**Comment by create3000** [comment]
--enable-parallel only enables some compile time parallelization features. Titania always uses threads for many tasks, ie. you can use --enable-release without any disadvantages.

**Comment by josiah47** [comment]
wow, thats much faster loading the big scene.

your right updated my gcc to 4.9.2 and it compiled and install and runs fine!
