### ISSUE TITLE
rendering movie view point only available for 'named' Viewpoints

### ISSUE THREAD

**Issue by splace** [create3000/titania#43]
Viewpoints could usually be named to make them available, but with a viewpoint in an externalProto having to modify this potentially shared resource is problematic.

**Comment by splace** [comment]
also

multiple instances of a prototype that contain a named viewpoint, (mean many viewpoints with the same name), do all appear in the dialog, but selecting any of them only actually selects the first.

**Comment by create3000** [comment]
Rendering a named viewpoint works essentially by loading the world through Browser.loadURL(url, parameter) and appending the viewpoint name to the url, ie a url like this: _file:///path/to/world.x3d#viewpointName_ (what spec says). There cannot be made a distinction between viewpoints with the same name found in different contexts. The same issue appears with an Inline file with a named viewpoint and the Inline file is included twice, than the name is two times available, than the first viewpoint found with _'viewpointName'_ is selected.

**Comment by splace** [comment]
i see, it is sensible to only jump into 'named' viewpoints from a URL, as to the spec., since proto's are made at run-time and can't be guaranteed to be there, but in a dynamic design env. the viewpoints can be read as they are currently, but obviously i see its another method to support.

its not straight-forward to 'hack' this, due to the proto chain and animated transform stack its in, i think i will need to have a duplicate proto, with a differently named viewpoint, then temporarily make the one i want to record from an instance of that.

it is a little surprising to be able to view from a viewpoint but not record from it. just saying. maybe the dialog should explicitly state this limitation?

**Comment by create3000** [comment]
You could add a proto field _viewpointName_ and give each proto instance an other name. Within the proto you could use Browser.currentScene.replaceNamedNode to give the viewpoint the name.

I know that if you don't want to modify your existing projects this is not an option.

**Comment by create3000** [comment]
> it is a little surprising to be able to view from a viewpoint but not record from it. just saying. maybe the dialog should explicitly state this limitation?

This could be an option.

**Comment by splace** [comment]
> I know that if you don't want to modify your existing projects this is not an option.

and its also about being better able to reuse them and any newly created ones.

i have been considering 'Inline'ing to do this kind of stuff, like specifying rendering mode or viewpoints, a bit like the semantic web, keeping the 'styling' separate, which also i think is fundamentally about reuse.

**Comment by create3000** [comment]
updated flatpak

**Comment by splace** [comment]
now shows only the one, first, named proto viewpoint.
