### ISSUE TITLE
[feature request] copy and clone in one step

### ISSUE THREAD

**Issue by splace** [create3000/titania#44]
if you only have one node selected, could clone do a copy first automatically.

and could 'create clone' be in the context menu? ('unlink clone' is there)

**Comment by create3000** [comment]
What I understand is:

1. Select one node anywhere in the scene graph.
2. Select Edit > Clone > Create Clone.
3. Create a clone of the selected node as last node of the root nodes.

Is this right?

BTW: clones can also be create by dragging and dropping them holding down _[Ctrl]+[Shift]_.

**Comment by splace** [comment]
yes, but wouldn't next sibling be better?

also 'create clone' in the context menu.

note: this, #45 and #25  are all about doing whats not surprising. (obviously i'm limited to what i find surprising, but this is the only way to get any perspective on a new users first impressions, which really can count.)

> BTW: clones can also be create by dragging and dropping them holding down [Ctrl]+[Shift].

from what i understand the menu/context menu, are almost like documentation, the first place a new user, should, look, these then show the keyboard shortcuts, which with practised use then become used.

**Comment by create3000** [comment]
There are also SFNode fields which do not have the possibility to add a sibling.

**Comment by splace** [comment]
ummm,  yes, and those have restrictions on where they go.

i was not liking the root positioning, because it might be a long way off, i suppose if its then selected its not that concerning.

**Comment by create3000** [comment]
https://github.com/create3000/titania/commit/16f546b784db6b13d9a74cadccbd2540504cb906 Added Outliner »Create Clone« menu item (#44). 
https://github.com/create3000/titania/commit/94e109a6725229ef759fa421c8b0faaddfedfe6b Reworked Outliner selection handling (#45).

**Comment by create3000** [comment]
updated flatpak

**Comment by splace** [comment]
works for me.

but...

this may have existed before, but may have been introduced....

if you use the context menu 'remove' all is fine, but if you use the delete key (with the clone selected) the node is removed but the indicator as to the number of clones, on the remaining clone, remains unchanged and does not subsequently correct.

**Comment by splace** [comment]
moving revealed bug to new issue, so enhancement is flagged as completed.
