### ISSUE TITLE
in walk mode avatar falls with no geometry below it.

### ISSUE THREAD

**Issue by splace** [create3000/titania#47]
AFAIK (and this test case backs it up http://www.web3d.org/x3d/content/ConformanceNist/BindableNodes/NavigationInfo/walk_typeIndex.html) the avatar shouldn't fall if there's nothing below it.

**Comment by create3000** [comment]
confirmed

**Comment by create3000** [comment]
The specification does not enjoin how a viewer works. It only say in the case of the WALK viewer:

23.4.4 NavigationInfo

"WALK" navigation is used for exploring a virtual world on foot or in a vehicle that rests on or hovers above the ground. It is strongly recommended that WALK navigation define the up vector in the +Y direction and **provide some form of terrain following and gravity** in order to produce a walking or driving experience. If the bound NavigationInfo's type is "WALK", the browser shall strictly support collision detection (see 23.3.2 Collision).

**Comment by splace** [comment]
yes, i also double checked and couldn't find a specification for this.

so it seems its a browsers choice, but it also seems that all, AFAIK, browsers choose to not fall with no geometry.

this is somewhat similar to the choice of height limit to be able step up, which can have an effect on the navigability of a world so probably should have been specified.
 
however there is another related issue, that wasn't even handled consistently, since its significantly harder and since there was no specification.....

what to do if animated geometry collides with the avatar?

although some of the best browsers did a reasonable job, it was common to find yourself moving inside geometry, which looks very amateurish/broken, (especially now given peoples familiarity with modern console games), so a 'ideal' solution would, i think, have to include the avatar being 'pushed' to a new location by the geometry, AFAIK this has never been implemented in any browser and is not necessary for standards compliance.

**Comment by create3000** [comment]
Version before there was an simpler implementation of collision detection and terrain following. This implementation results in that the viewer does not fall with no geometry below it. But X_ITE and Titania now have a very optimized version of collision detection and terrain following which results in that the viewer also falls when there is no geometry below it. I think there is no reason why the viewer should not fall. In real world gravity always occurs. If the author of a scene do not wish that gravity occurs he/she should use a FLY viewer.

**Comment by create3000** [comment]
> what to do if animated geometry collides with the avatar?

> i think, have to include the avatar being 'pushed' to a new location by the geometry

This is right.

Also, if the viewer is moving and colliding against a wall at an acute angle, the viewer should not stop, he/she should slide along the wall.

**Comment by splace** [comment]
the original problem faced was with Prototype component libraries, i wrote, which brake only for Titania/X_ITE.

with a component, to be instanced to make up a final scene, they can't have a surface, and you need to test them separately, which is hard if the 'walk' mode is needed and doesn't work without some surface.

but i now see i can add an instance and a surface OUTSIDE the Proto in the lib file, (just for testing) this will make them work in isolation and not cause multiple surfaces to be added to the final scene.

and this then means they work for any complaint browser.

**Comment by splace** [comment]
> this is somewhat similar to the choice of height limit to be able step up, which can have an effect on the navigability of a world so probably should have been specified.

my mistake, this was always specified, by the third of the numbers in the avatarSize field
