### ISSUE TITLE
Different Rotation Start point in a Route

### ISSUE THREAD

**Issue by josiah47** [create3000/titania#5]
I have 2 inline objects in a scene one output connected to input of another. Both have a default starting rotation. but when i change the rotation of the one it changes the other to the same rotation. Is it possible to have it increment the other from its default rotation? 

Example: in your info.x3dv
![screenshot - 032515 - 09 55 18](https://cloud.githubusercontent.com/assets/870875/6826084/6ff3bcc4-d2d5-11e4-9ece-afd342a6a50b.png)

if you want both those to turn and not interfere with each other, what would be the best way to achieve this?

**Comment by create3000** [comment]
If you connect two objects, assume these are the rotation fiels of two Transform nodes, then they »share« the same rotation. If you want to animate objects, give the Keyframe Animation Editor a try, thats the easest way to animate objects. Sure you could use a Script node to achive the same effect, but then you have to deal with rotation algebra. The editor is explained here: http://titania.create3000.de/documentation/keyframe-animation-editor/

**Comment by josiah47** [comment]
I was using the keyframe animation editor, which is cool, similiar to blenders which i haven't used in years. it was working just very tidious mouse clicking work, going to tree xnee out for mouse macro. unless there is a quick way to say rotate this object 360 degrees within this time period and this many frames per second... but i doubt it. I am currently doing it as per your documentation.

**Comment by create3000** [comment]
The basic nodes and steps of an animation are:
TimeSensor -> interpolator node -> receiver
where the interpolator node could be a simple ScalarInterpolator for float fields or a OrientationInterpolator for rotation fields, the receiver could be any node such as a Transform or Viewpoint. The Keyframe Animation Editor creates the appropriate nodes and connects them automatically and lets you scroll through the animation. First you must select a grouping node like Transform where to add the animation, then click on Create New Animation. Then select the node to animate and click on Add Member and then you can create keyframes.

**Comment by josiah47** [comment]
Okay then I got it right. Thanks for the explanation.

**Comment by create3000** [comment]
The second way is if you want a rotation offset for the second object, create a parent Transform and rotate this as desired.
