### ISSUE TITLE
hierarchy view not updating to show non-default field values when created by visual editor. 

### ISSUE THREAD

**Issue by splace** [create3000/titania#50]
if you use the visual editor to change from the default, (not displayed), value of a Transform field, (say to move away from the origin), the value of the field is not displayed until you, say, contract and expand the hierarchy view.

**Comment by create3000** [comment]
This is right. There is still something the user has to do. This cannot be done automatically. BTW: Hold down the _Shift_ key and click expand will fully expand the node.

**Comment by splace** [comment]
OK, i reported because i felt it to be a well adhered-too paradigm; that changing the folding of a hierarchy, contract/expand etc., never results in changing the displayed content, that is, what is actually being displayed was always valid/'current'. so possibly contacting it so as to hide 'obsolete' content would be fine.

i understand that there is a balance, and not excessively expanding the code base just to alleviate edge cases is highly desirable, however a lot of edge cases can be indicative of a pattern mismatch.

**Comment by splace** [comment]
>  Hold down the Shift key and click expand will fully expand the node.

yes, this seems a vital feature i had not found. i did see that when all values were default, you got fully expanded, but after one non-default the others were hidden and i had become a bit stuck.

also i notice a similar effect to the OP; if you select (with shift) then deselect and select again (without shift) the fields are still fully expanded, you need to compress and expand to remove them from being displayed. however this way round is fine since an 'invalid' state is never displayed, just unnecessary default values.

**Comment by splace** [comment]
>  from #25......
>  If single click is enabled to select in Outline Editor, then it is easy to release the selection or wrongly select something. With double click the selection is more stable and it is harder to make mistakes

FWIW  from a very limited new users point of view, i can not really see how this would increase mistakes, and now it appears a 'natural' use of double-click has had be relegated to shift double-click.
