### ISSUE TITLE
trying to remove a default value field from nodes that are default-expanded, causes the node to be removed.

### ISSUE THREAD

**Issue by splace** [create3000/titania#53]
[zipped mp4](https://github.com/create3000/titania/files/2430802/Peek.2018-09-29.15-48.zip)

**Comment by create3000** [comment]
This menu item belongs to the **node.** like the »Create Clone« menu item below. Menu items are grouped indicated by separators (horizontal lines).

**Comment by splace** [comment]
> Menu items are grouped indicated by separators (horizontal lines).

i see now they all work on the containing node, but that seems to apply to all items in the menu, what do the horizontal lines indicate?

and

how do i remove a field?

**Comment by create3000** [comment]
Fields cannot be removed, but you can set them to the default value for the node. To do that, expand the field, click the value of the field to edit the value, then right click to open the context menu, then choose »Reset To Default Value«. The field will not be shown after you collapse and expand the node. To show the field again _Shift-expand_ the node.

http://create3000.de/titania/documentation/using-the-outline-editor/

Only fields from Script nodes and shader nodes can be removed, to do that select the Script node and open the Node Editor from the Toolbar, select the first tab »Node Properties« at the right, and then select the second tab »User-Defined Fields« at the bottom.

http://create3000.de/titania/documentation/script-editor/

Only fields from PROTO's can be removed, to do that open the Prototype Editor from the Toolbar and select a proto.

http://create3000.de/titania/documentation/editing-prototypes/
