### ISSUE TITLE
[java/vrmlscript] setting SFRotation values components individually results in complex order-dependent interaction.

### ISSUE THREAD

**Issue by splace** [create3000/titania#54]
seems to be due to quaternion 'normalisation' after each component being set.

minimal test case:
````
#VRML V2.0 utf8

DEF c1 Transform {children Shape{geometry Cone{} appearance Appearance {}}}
DEF c2 Transform {children Shape{geometry Cone{} appearance Appearance {}}}

DEF	rotScript Script{
eventOut SFRotation rot1
eventOut SFRotation rot2
url["javascript:
function initialize (){
	rot1[0]=1;
	rot1[1]=0;
	rot1[2]=0;
	rot1[3]=1.57;
	rot2= new SFRotation(1,0,0,1.57);
};
"]
}

ROUTE rotScript.rot1 TO c1.rotation
ROUTE rotScript.rot2 TO c2.rotation

````

this didn't seem to be the case in any 'old' browsers, which show these two shapes moved identically.

**Comment by create3000** [comment]
Updated flatpak.

**Comment by splace** [comment]
confirmed fixed.

**Comment by splace** [comment]
just wondering if it would be best if i duplicate this report, including immediately closing it, on x-ite. so it appears in searches and people know what version to get if they experience it?
