### ISSUE TITLE
AUR package don't build

### ISSUE THREAD

**Issue by DraGiuS** [create3000/titania#55]
/usr/bin/sed: can't read Projects/aurpackages/titania-git/src/titania/libtitania-standard/libtitania-standard.la: No such file or directory
libtool:   error: 'Projects/aurpackages/titania-git/src/titania/libtitania-standard/libtitania-standard.la' is not a valid libtool archive
make[2]: *** [Makefile:481: libtitania-stream.la] Error 1
make[2] : on quitte le répertoire « /home/yosh/Git Projects/aurpackages/titania-git/src/titania/libtitania-stream »
make[1]: *** [Makefile:462: all-recursive] Error 1
make[1] : on quitte le répertoire « /home/yosh/Git Projects/aurpackages/titania-git/src/titania »
make: *** [Makefile:394: all] Error 2
==> ERREUR : Une erreur s’est produite

**Comment by create3000** [comment]
We do not actively support the AUR package anymore. Please use the flatpak, this is a convenient way to provide a software package.

**Comment by create3000** [comment]
See also http://create3000.de/titania/download/.
