### ISSUE TITLE
Inlined NavigationInfo set to first bound.

### ISSUE THREAD

**Issue by splace** [create3000/titania#56]
if an Inline is before (but not if its after) a NavigationInfo in the scene, then the NavigationInfo from the Inlined scene is being bound first.

http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/core.html#BindableChildrenNodes
> During read, the first encountered <bindable node> in each layer is bound by pushing it to the top of the <bindable node> stack for that layer. Nodes contained within files referenced by Inline nodes, within the strings passed to the Browser.createX3DFromString() method, or within X3D files passed to the Browser.createX3DFromURL() method (see Part 2 of ISO/IEC 19775) are not candidates for the first encountered <bindable node>

**Comment by create3000** [comment]
Updated flatpak and X_ITE alpha.

**Comment by splace** [comment]
works as expected, also in X_ITE 408
