### ISSUE TITLE
Precision Placement Panel Explanation

### ISSUE THREAD

**Issue by josiah47** [create3000/titania#6]
I couldn't find a help on this panel.

Can you explain this panel a little bit, especially the rotation part and the logic of x and y not have angle but z does? and when using the -/+ button then number just keeps going up and the x/y/z-Axis don't ever hit a max but just slow down the turn of the object?

Thanks,

**Comment by create3000** [comment]
The PPP shows and lets you edit the Transform node fields and other nodes fields too. Rotation: shows the plain rotation values. A rotation consists of an axis part and an angle. To rotate an object it is often more feasible to use the rotation tool, ie. double click on a selected object in the browser window.

**Comment by create3000** [comment]
You can hold down the Ctrl-key while rotating to snap to predefined rotations while using the rotation tool.

**Comment by josiah47** [comment]
Sweet, that works, is there a way to define the predefined snap points? like every angle or every 10 degrees...

**Comment by create3000** [comment]
No, not yet.

**Comment by create3000** [comment]
Wrote some documentation for Precision Placement Panel, have a look at:
http://titania.create3000.de/documentation/precision-placement-panel/

**Comment by josiah47** [comment]
Thanks, don't know if you mention in a different section of the documentation for the rotation tool, but maybe mention the 'You can hold down the Ctrl-key while rotating to snap to predefined rotations while using the rotation tool.' I have notice that you need to wait for the rotation ring to highlight its color before the snap will work, it is very buggy for me and scripting it with a mouse macro is flaky. but maybe that has something to do with some else. i have been able to move the mouse so quickly into the ring that it doesn't activate the highlight. but then if you move it in and out again slower it works. maybe thats a little hint for the bug. I can open a new issue for that if you want?
Also I am still confused why the z as a angle field and x and y don't, most likely because I don't fully understand all this stuff...

**Comment by create3000** [comment]
Maybe you should work a little bit slower. First: The rotation rings doesnt have to be covert by the bbox or the geometry then picking cannot work. Second: rotation in 3D isn't easy to understand, but there are other rotation system like euler angle that might be, so it isnt your fault. But that needs to be implemented in some way first.

**Comment by josiah47** [comment]
lol, I guess for now i'll just stick to the rotation tool with snapping

**Comment by create3000** [comment]
Fixed bug with rotation adjustments in Precision Placement Panel and other use cases. Before, the four values x, y, z and angle are set independently one after one. But with rotations they all four must be set at one time. This is fixed now. Take a box. Try setting the axis to 1,1,1 and then change the angle. The box should now rotate about the front upper right corner (x,y,z is the axis about the rotation occurs).

**Comment by create3000** [comment]
Reworked documentation:
http://titania.create3000.de/documentation/precision-placement-panel/

**Comment by josiah47** [comment]
Okay, created this test scene, which mimics another scene i have bigger data.
http://filebin.ca/1wIIlEdfHC4D

I want to rotate those cubes on the blue axis don't know if its x or y or z by quick glance, not really indicated anywhere.

rotate both cubes on blue axis full 360? does it work for you? it goes fast for me and then slows down but never reaches full 360, I can't rotate on other axis because the "cubes" are inline and part of a bigger scene.

This is using the PPP for accurate angle rotation of course

**Comment by josiah47** [comment]
Basically if you have the PPP up and then use the rotation tool with CTRL you see both x and y values change at the same time. Can this be done some how with the PPP? another axis field put in to control the that axis and change both values simo. since I can't change its default rotation in the scene and use the z axis.

**Comment by create3000** [comment]
The axis-angle-rotation is not always easy to understand. To make it clear the axis is a normalized vector, and then there is a fourth value the angle. The axis is the axis about which the rotation occurs. Below is an image the describes this:

![axis-angle-rotation](https://cloud.githubusercontent.com/assets/2930196/6875630/a4551944-d4c0-11e4-8bb3-f74e21de4a90.png)

You can see the axis (white vector) changing in the preview next to the input widgets.

**Comment by create3000** [comment]
To start with axis-angle-rotation use as axis the X-axis (1,0,0) or the Y-axis (0,1,0) or the Z-axis (0,0,1) and then change the angle.

**Comment by josiah47** [comment]
Okay I think I understand now what needs to happen.
http://filebin.ca/1wbNEiPk1Rzs

If you want to spin the cube and cylinder around the X axis and keep its rotation on the Y axis the same to the windmill, I would need to make a parent group(transform im guessing)  for the cube and cylinder, then I can change the X axis with out effecting the Y axis...

**Comment by create3000** [comment]
Yes, thats right and common practice.
