### ISSUE TITLE
mpeg1 movieTexture frame-rate very inconsistent.

### ISSUE THREAD

**Issue by splace** [create3000/titania#60]
http://www.web3d.org/x3d/content/ConformanceNist/Appearance/MovieTexture/default_start2.x3d

initially was blank, then single random frame, then plays once, is there some background processing delay going on?

**Comment by splace** [comment]
i notice after third restart, it has started looping.

but after 10+ loops, freezes.

also; after a restart, for one cycle, it is smooth, but then it becomes jerky, then stops.

**Comment by create3000** [comment]
Titania uses GStreamer https://gstreamer.freedesktop.org/ to render movies, file you bug there, or use a modern movie file format like MP4.

**Comment by splace** [comment]
works in latest flatpak.
