### ISSUE TITLE
"paint polygon" tool produces no colours.

### ISSUE THREAD

**Issue by splace** [create3000/titania#63]
see file, (has TextureCoordinate but no actual texture.)

[scene.zip](https://github.com/create3000/titania/files/2497450/scene.zip)

specifically; i created a IFS from a ElevationGrid by 'smash'ing it, using the geometry editor, then painted whole faces using the tool.

**Comment by splace** [comment]
i was expecting this tool to produce color/colorIndex fields, but i see you can mix vertex and face colours in the same IFS, which the color field can't handle.

but by using a texture how are you able to progressively edit, can the tool recover the palette and face/vertex settings?

**Comment by create3000** [comment]
The Geometry Editor is only for modeling the geometry on polygon base. You have selected the 'paint selection tool' in the tool palette. Right click on the Polygon Selector button opens a menu for further options.

In the Toolbar there are more editor, also the Paint Polygon Editor, which is for coloring polygons. There is also the Texture Mapping Editor to precisely map textures.


![paint](https://user-images.githubusercontent.com/2930196/47264718-67ad2080-d51c-11e8-923d-038590563ede.png)

**Comment by create3000** [comment]
Color Per Vertex Editor http://create3000.de/titania/documentation/paint-a-single-or-more-polygons/
Texture Mapping Editor http://create3000.de/titania/documentation/accurately-map-textures/

**Comment by splace** [comment]
what you say isn't explaining what when wrong for me.

i 'smashed' an ElevationGrid and so got polygon base, i then used polygon editor, i saw colours and made the pattern i wanted, when i closed the editor i had nothing. (see file)

**Comment by create3000** [comment]
Have you clicked the »Apply« button before you closed the Polygon Coloring Editor?

**Comment by splace** [comment]
no i didn't, going back i see the button was just off the bottom of my screen, since this is the first time i've seen a control that needed 'applying', i didn't think to look.

should there be a warning?

also 

should the tool generate texture coordinates if its not applied?
