### ISSUE TITLE
unable to add MultiTextureTransform node.

### ISSUE THREAD

**Issue by splace** [create3000/titania#65]
documentation says it's Titania but not x-ite, so tried switching off compat. mode but still no way to generate i can find. 

Note: this is for conversion of a world using Cortona's AdvancedAppearance ("http://www.parallelgraphics.com/vrml/proto/Cortona/extensions.wrl#AdvancedAppearance") node, which seems to have basically the same functionality just a different structure.

**Comment by splace** [comment]
also, doesn't seem to  be a 'clean' way to add textures to a MultiTexture.texture field.

you CAN do it by making a dummy shape giving that a texture then dragging it into the MultiTexture.texture field.

**Comment by create3000** [comment]
Use drag an drop feature in OutlineEditor to compose a MultiTexture.
