### ISSUE TITLE
Crash upon add new new keyframe animation

### ISSUE THREAD

**Issue by josiah47** [create3000/titania#7]
Initializing widget: AnimationEditor
Load Time: 0.836748
FPS: -nan
Done parsing into scene: file:///home/jan/.local/share/titania/tools/library/ToolShader.x3dv.
Done parsing into scene: file:///home/jan/.local/share/titania/tools/BoundingBox.x3dv.
Done parsing into scene: file:///home/jan/.local/share/titania/tools/library/ToolShader.x3dv.
Done parsing into scene: file:///home/jan/.local/share/titania/tools/BoundingBox.x3dv.
###### #### Titania/X3D/Execution/Scene.cpp:81: in function '~Scene': file:///home/jan/.local/share/titania/tools/library/ToolShader.x3dv

Done parsing into scene: file:///home/jan/.local/share/titania/tools/library/ToolShader.x3dv.
Done parsing into scene: file:///home/jan/.local/share/titania/tools/library/BooleanSwitch.x3dv.
Done parsing into scene: file:///home/jan/.local/share/titania/tools/TransformTool.x3dv.
Done parsing into scene: file:///home/jan/.local/share/titania/tools/library/ToolShader.x3dv.
Done parsing into scene: file:///home/jan/.local/share/titania/tools/library/BooleanSwitch.x3dv.
Done parsing into scene: file:///home/jan/.local/share/titania/tools/TransformTool.x3dv.
titania: symbol lookup error: titania: undefined symbol: _ZNSt6vectorIPN7titania3X3D6X3DPtrINS1_11X3DBaseNodeEEESaIS5_EE6insertEN9__gnu_cxx17__normal_iteratorIPS5_S7_EERKS5_

something to do with me missing something else now?

here is my gcc -v just incase 

Using built-in specs.
COLLECT_GCC=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.2/gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/4.9.2/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /var/tmp/portage/sys-devel/gcc-4.9.2/work/gcc-4.9.2/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/usr --bindir=/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.2 --includedir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/include --datadir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.9.2 --mandir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.9.2/man --infodir=/usr/share/gcc-data/x86_64-pc-linux-gnu/4.9.2/info --with-gxx-include-dir=/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.2/include/g++-v4 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/4.9.2/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 4.9.2 p1.2, pie-0.6.2' --enable-libstdcxx-time --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --enable-multilib --with-multilib-list=m32,m64 --disable-altivec --disable-fixed-point --enable-targets=all --disable-libgcj --enable-libgomp --disable-libmudflap --disable-libssp --enable-lto --with-cloog --disable-isl-version-check --enable-libsanitizer
Thread model: posix
gcc version 4.9.2 (Gentoo 4.9.2 p1.2, pie-0.6.2)

I have make uninstall and then make installed to make sure libraries aren't of date.

**Comment by create3000** [comment]
It is a little bit hard to port a Ubuntu distribution to Mint. The error:

titania: symbol lookup error: titania: undefined symbol: ZNSt6vectorIPN7titania3X3D6X3DPtrINS1_11X3DBaseNodeEEESaIS5_EE6insertEN9__gnu_cxx17__normal_iteratorIPS5_S7_EERKS5

can occur when a dependent library (where __normal_iterator is defined) was compiled for other version of GLIBC (newer version or much older), that you currently have. __normal_iterator is defined in the C++ Standard Template Library (STL). The means if you want to compile Titania with gcc 4.9.2, you have to compile all dependencies with gcc 4.9.2, or save that work and switch back to gcc 4.8.

**Comment by josiah47** [comment]
Okay recompiled my whole system with gcc 4.9.2 and titania is working fine now. Thanks.
