### ISSUE TITLE
[INFO] Cosmo 1.0 working world with incompatible proto declaration events, produces error on load.

### ISSUE THREAD

**Issue by splace** [create3000/titania#70]
example:

````
#VRML V2.0 utf8

PROTO Plane [
exposedField SFFloat stat 0
]{
PositionInterpolator{ set_fraction IS stat}
}
````

relevant spec.:  http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/concepts.html#PrototypeSemantics

found when an old, claimed 'Cosmo 1.0 tested', world wouldn't load.

**Comment by create3000** [comment]
No, this connection is forbitten.

If the proto interface has an inputOnly field, then it can be referenced by IS statement within the body to an inputOutput field, but the other way round is forbitten.

**Comment by splace** [comment]
when i initially went to check the spec. i thought you were right, and the file i found indicated Cosmo had it wrong.

but then i re-read it and was sure you were wrong (this is somewhat based on just being unable to understand why this way round, the reverse seems better.)

i now re-read it again and think you are right!

however; for me the use of the term 'undefined' means it can do anything and does not produce an error, but in different places it IS referred to as an error, which, to me, means an error message SHOULD be produced.

this means the maker of the 'problem' world misunderstood, and never noticed some of the code didn't work, no error message, or it did work just by accident (undefined).

not sure that checking Cosmo would achieve anything, but here it is, for ref:  [FARO3DN4.WRL.GZ](https://github.com/create3000/titania/files/2620783/FARO3DN4.WRL.GZ)
