### ISSUE TITLE
[REGRESSION] script access to fields of nested PROTO's instance, causing 'undefined' error.

### ISSUE THREAD

**Issue by splace** [create3000/titania#71]
used to work, a month or so ago, and still works in X_ITE v4.2.10-464.

below causes JavaScript error:- "<< instance >>.<< field >> is undefined";

a PROTO containing a nested PROTO's instance being USE'ed by a SCRIPT, which then attempts to access the instances fields.
(the PROTO instance and the SCRIPT not the first node in the body.)

**Comment by create3000** [comment]
Titania in its latest version uses now the latet SpiderMonkey JavaScript engine. But this means that the node handling is different than with the old version. This leads to that the new JavaScript engine implements the Script node _directOutput_ field. See: http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/scripting.html#directoutputs. That means if you do something like this:

```
function foo (node)
{
   print (node .translation) // direct access node's translation field for reading
   node .translation = new SFVec3f (); // direct access node's translation field for writing
}

```
You must now set the Script nodes _directOutput_ field to TRUE.

**Comment by create3000** [comment]
![script-editor-direct-output-button](https://user-images.githubusercontent.com/2930196/51242576-994d5080-1980-11e9-953d-cf80de8a8938.png)
Script Editor _directOutput_ button

**Comment by splace** [comment]
my interpretation of the spec. is that with 'DirectOutput = FALSE', all output needs to be by explicit event fields and ROUTES, this seems clear (and informs the name), but that you are still able to read node type fields, whether they are 'clones' or not.

AFAIK. this is how the main 'old' browsers all did it, so this difference will possibly break substantial content and the broken content will be the most advanced and least likely to ever get adjusted.

FYI.  from reading a lot of the original 3rd party guides, DirectOutput has really never been clearly understood. one recommendation was just to set it TRUE and don't worry about it. (if this recommendation was followed then the content will be OK.)

FWIW.  it seems to me that DirectOutput is just an optimisation, (only really reducing code size) and for it to have caused such problems is really unfortunate, should have defaulted to TRUE, or never existed.

**Comment by splace** [comment]
(checking i was not reading an obsolete specification.)

extracted from:  http://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/scripting.html

> Once the script has access to a VRML node (via an SFNode or MFNode value either in one of the Script node's fields or passed in as an eventIn), the script is able to read the contents of that node's exposed fields. If the Script node's directOutput field is TRUE, the script may also send events directly to any node to which it has access, and may dynamically establish or break routes. If directOutput is FALSE (the default), the script may only affect the rest of the world via events sent through its eventOuts. The results are undefined if directOutput is FALSE and the script sends events directly to a node to which it has access. 

this is basically the same wording as in the original vrml 2.0

**Comment by splace** [comment]
could you check this and confirm, seems clear to me and is causing problems.

**Comment by create3000** [comment]
> but I suspect it's on by default in modern browsers.

https://sourceforge.net/p/freewrl/mailman/message/29071526/

**Comment by splace** [comment]
this isn't really the problem.

the spec says:

> the script is able to read the contents of that node's exposed fields

directoutput has no effect on reading exposed fields of node type, (indirectly accessed through the scripts fields etc.) you can always do it. (the issue is that this has stopped happening)

**Comment by splace** [comment]
NOTE: the title refers only to a user made node (proto instance) being used by a script, both of which are inside another proto, i have not confirmed what happens with builtin nodes or with a script not inside a proto.

**Comment by splace** [comment]
confirmed working in latest flatpak.

(sorry i think my explanation was poor/confusing.)
