### ISSUE TITLE
TextureCoordinateGenerator not working

### ISSUE THREAD

**Issue by splace** [create3000/titania#79]
With the current downloaded version, the texture does appear now, but the example given in #78 is not functioning, the texture coords are just the default, whatever the value of mode.

**Comment by create3000** [comment]
TextureCoordinateGenerator is not implemented in X_ITE and Titania X_ITE mode. If you disable X_ITE Compatibility then TextureCoordinateGenerator is working but only partially.

**Comment by splace** [comment]
I didn't have X-ite mode on.

since its only 'partially support' and none of the common ones work, i (others?) have no way to know what should work.

i think you should remove it being supported in the documentation.

**Comment by create3000** [comment]
The TextureCoordinateGenerator node is now fully implemented in X_ITE and in Titania X_ITE Compatibility mode and right to be tested. The TextureCoordinateGenerator Editor has now also new features.

**Comment by splace** [comment]
confirmed working in flatpak. nice.
