### ISSUE TITLE
PeaseBlossom

### ISSUE THREAD

**Issue by josiah47** [create3000/titania#8]
Okay I have to ask, why that name and what in particular does it cover?

**Comment by create3000** [comment]
PB is a study in writing a JavaScrpt engine. It covers only the functionality needed by the 3D tools. Most parts of these tools are written in X3D. For normal JavaScript SpiderMonkey 1.8 is uses. But there is a problem. When more than 100 Script nodes are in a Scene, lets say 400, then the creation of a JavaScript context dramatically slows down. This is a major problem for the Transform Tool when selecting a lot objects. On the other hand SM 1.8 runs very slick. But is not up to date. For that reason, I switched to SM 24 (I have a working folder of that) but SM 24 has other Garbage Collection, ie. long breaks occur when I run GC. The same with V8 (I have a working folder too) I decided to stay by SM 1.8 until I have solution for that GC problem.
