### ISSUE TITLE
background sky color not clamping to last value (sometimes)

### ISSUE THREAD

**Issue by splace** [create3000/titania#85]
```
#VRML V2.0 utf8 Titania V4.4.4

WorldInfo {
  title "bacground-bug"
}

Background {
  skyAngle [
    1.571,
    1.833,
    1.745
  ]
  skyColor [
    1 1 1,
    0.8 0.91 1,
    0.67 0.76 0.85,
    0 0 0
  ]
}
```
![background-bug](https://user-images.githubusercontent.com/1234848/55283350-1f125280-5359-11e9-9f65-3516ec331103.jpg)

**Comment by create3000** [comment]
skyAngle [
    1.571,
    1.833,
    1.745
  ]

skyAngle values must be in ascending order. In your example the middle value is the highest, which is wrong.

**Comment by create3000** [comment]
If you are unsure how to create a Background use the Background Editor of Titania.

![Bildschirmfoto von 2019-04-04 09-28-01](https://user-images.githubusercontent.com/2930196/55537268-194fa080-56bc-11e9-9b77-cf174563cc87.png)

**Comment by splace** [comment]
sorry, from a downloaded world, i did not notice.
