### ISSUE TITLE
background not showing in export when alpha channel on

### ISSUE THREAD

**Issue by splace** [create3000/titania#86]
neither texture box or color gradients.

**Comment by create3000** [comment]
This is a feature not a bug.

**Comment by splace** [comment]
OK, but what if you want the background and it has transparency?

**Comment by splace** [comment]
>  but what if you want the background and it has transparency?

OK, i now see, because skycolor defaults to black (and covers complete world, by going right down to nadir), and color's can't be transparent, and sky is behind texture skybox, you can't have any transparency in a background.
