### ISSUE TITLE
layerset backgound issues

### ISSUE THREAD

**Issue by splace** [create3000/titania#87]
has a background 'black pettel shape' when nothing in layer 0 (default).

```
#VRML V2.0 utf8 Titania V4.5.0

LayerSet {
  activeLayer 1
  order 1
  layers Layer {
    children DEF Box Transform {
      children Shape {
        appearance Appearance {
          material Material { }
        }
        geometry Box { }
      }
    }
  }
}
```
![Screenshot from 2019-04-16 17:35:14](https://user-images.githubusercontent.com/1234848/56228541-f2a44900-606f-11e9-872e-c5becf5b2948.png)

also affecting builtin 'recent' dialog

![Screenshot from 2019-04-16 17:45:22](https://user-images.githubusercontent.com/1234848/56228503-e0c2a600-606f-11e9-82f5-aa52e75c3e96.png)

**Comment by create3000** [comment]
If the background is transparent or no background (layerset) is present the widget background is shown with the Titania logo.

**Comment by splace** [comment]
OK, but..... i find it quite confusing.....

>  If the background is transparent 

Background nodes can't be transparent, i guess you mean no geometry? 

but then why doesn't this happen in an empty scene, but does for an empty layer? how are they really different?

when this happens requires some deep understanding, so initially its baffling.

obviously the same scene doesn't do this in x-ite, i think it should be WYSIWYG (maybe just in x-ite compat. mode)

notice: it stops you reading the file names in the recent dialog.

**Comment by splace** [comment]
>>    If the background is transparent

> Background nodes can't be transparent, i guess you mean no geometry?

i see x3d has Background nodes that now do support Transparency, via a new field, i guess this was introduced in concert with layers, no point before.

**Comment by splace** [comment]
[enhancement] allow choice of transparency representing background.

**Comment by splace** [comment]
FYI  if you use the X3D transparency field of Background and save as VRML2, it is included, so, i think, a strictly parsing VRML browser will report as an error.

**Comment by create3000** [comment]
Allowing to choose if the background is rendered is a good option, because it makes it more transparent to the user what happens if he exports an image.
