### ISSUE TITLE
[regression] recent builds lock up on previously working world.(also in x-ite)

### ISSUE THREAD

**Issue by splace** [create3000/titania#88]
https://github.com/vrml2/tnakgame/blob/master/tnakgame.wrl

lockup when click 'play', after 'generate'.

**Comment by splace** [comment]
after noticing it IS actually also not working in x-ite, (i think i used an older version when i said it worked) i did some testing...

working v4.2.6a-406 and before
not-working X_ITE v4.4.7a-712 and after

firefox performance output, seems to show it never returning from a frame draw. (guess)
![Screenshot from 2019-04-28 23:45:59](https://user-images.githubusercontent.com/1234848/56871059-5a637800-6a10-11e9-9113-494e1480852e.png)
:

**Comment by create3000** [comment]
There should be something wrong with the world, please file a bug to the world authors.

**Comment by splace** [comment]
since this works in other browsers and x-ite/titania up until recently, (and a lockup should never be the consequence of a worlds contents, DOS ), it seems virtually impossible it isn't a bug in your code.

i was thinking of dis-assembling that world to make a simple demonstration case, but since that would involve so much more work for me, than for you, i did not.

if you would consent to look at something like that, i will still do that, if you are not interested please remove me from authorship, the list of x-ite effecting wontfix/non-compliances/bugs is now too long for me, it indicates our goals are too misaligned.

for ref. #74, #88, #47, #89, <a class="issue-link js-issue-link" data-error-text="Failed to load issue title" data-id="370685715" data-permission-text="Issue title is private" data-hovercard-type="issue" data-hovercard-url="/create3000/x_ite/issues/32/hovercard" href="https://github.com/create3000/x_ite/issues/32" aria-label="#32, not playing mpeg 1 movie">#32</a>, #109
