### ISSUE TITLE
Transform Group not showing rotation

### ISSUE THREAD

**Issue by josiah47** [create3000/titania#9]
As you can see in the attachment why does the one have a rotation, and the other not?

I did change the rotation on both but only the one had the rotation row come in it.
Also tried adding it to a key frame animation. maybe that would trigger it...

![screenshot - 033015 - 09 46 06](https://cloud.githubusercontent.com/assets/870875/6898112/14195a86-d6c6-11e4-94a3-28eb08b7216c.png)

**Comment by josiah47** [comment]
I reloaded the document and it seems to have brought it up now.

**Comment by create3000** [comment]
Some nodes have a lot of fields. So it makes the OutlineEditor more clear to show up only the fields that have other values than the default. To show all fields press the Shift-key and than click onto to expander arrow.  If you expand a node that has only default values for its fields than all fields are shown.

**Comment by josiah47** [comment]
Sweet I now see that in the documentation, don't know if it was there before or not. I have to apologize if it was.
