### ISSUE TITLE
Info/question - clean code generation?

### ISSUE THREAD

**Issue by anonimo82** [create3000/titania#90]
Hello there.
Does Titania generate clean X3D code?
Human readable?

What language is the editor written in?

Thanks for help.

**Comment by create3000** [comment]
![Bildschirmfoto von 2019-04-27 18-15-56](https://user-images.githubusercontent.com/2930196/56852269-5b65ae00-6919-11e9-89a8-ceee4afdd577.png)

Yes, in the File Save Dialog you can control the 'output style' on the left. Options 'nicest', 'compact', 'small', and 'smallest' are available. As well as you can select the encoding, for instance 'XML', the popular 'VRML Classic', and 'JSON'.

**Comment by anonimo82** [comment]
Thanks.
What language is the editor written in?

**Comment by create3000** [comment]
The Titania Editor is entirely written in C++. Some parts are plugs that are in X3D.
