### ISSUE TITLE
last flatpak not finding base

### ISSUE THREAD

**Issue by splace** [create3000/titania#92]
```
flatpak install --user --from http://code.create3000.de/repos/titania.flatpakref
error: The application de.create3000.titania/x86_64/stable requires the runtime org.gnome.Platform/x86_64/3.30 which was not found
```

**Comment by create3000** [comment]
This is a know issue.

**Comment by create3000** [comment]
Should update now without the additionally lines.

**Comment by splace** [comment]
still the same here, i'll try again tomorrow.

**Comment by create3000** [comment]
try
`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
and then update.

**Comment by splace** [comment]
> try
> `flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`
> and then update.

no effect.

**Comment by splace** [comment]
after finding update failed, i tried;

* a separate install of the base... but NOT FOUND (isn't this the problem?)
* then uninstalled everything and tried an install, and got the OP this is when i reported.

so i can't actually do an update, but since a clean install isn't working, seems no point.

**Comment by create3000** [comment]
Have installed the FlatPak on a fresh installation of Ubuntu, with no flatpak preinstalled, and it works fine.
Have you tried `flatpak remotes` and then `flatpak remote-delete REMOTE_NAME` and then a new install from flatpakref: `flatpak install --user --from https://code.create3000.de/repos/titania.flatpakref`?

**Comment by splace** [comment]
well there was gnome and de.create3000.titania-origin

which i deleted, but no difference.

BTW there is also flathub, which i presume shouldn't be deleted.

**Comment by splace** [comment]
i've removed and reinstalled flatpak, no difference.

**Comment by splace** [comment]
```
flatpak --ostree-verbose --system install flathub -y org.gnome.platform/x86_64/3.30
F: Adding GPG keyring data from flathub.trustedkeys.gpg to verifier
error: Error searching remote flathub: Can't find ref org.gnome.platform/x86_64/3.30
```

**Comment by splace** [comment]
are you pulling from some development repo?

**Comment by splace** [comment]
OK, on a hunch i tried installing gnome separately to SYSTEM.

> flatpak install --system flathub org.gnome.Platform/x86_64/3.30

then 

> flatpak install --user --from http://code.create3000.de/repos/titania.flatpakref

and its now working, not clear at all to me the problem.

BTW looking great, my system theme is being used AND the folder sorting issue #31 is fixed. 

fell free to close or keep open to triage?

**Comment by splace** [comment]
```
flatpak --version
Flatpak 1.0.8

```

**Comment by splace** [comment]
updated to 1.2.4

big advances, seems to work, but its a new install, guess will wait to see what happens after a platform update.

**Comment by create3000** [comment]
Maybe the flatpak version was the issue. You can with `flatpak remote-delete REMOTE` delete all reference from this remote and then reinstall.

**Comment by create3000** [comment]
Also using version 1.2.4.
