### ISSUE TITLE
'open recent' dialog can be edited

### ISSUE THREAD

**Issue by splace** [create3000/titania#94]

**Comment by create3000** [comment]
This is useful for examining and learning.

**Comment by splace** [comment]
if you 'open as current scene' with the rotor PROTO, then try to 'open recent' nothing happens, i guess because its there but hidden.

**Comment by splace** [comment]
i notice, if you open 'open recent' with pause on, it does not matter, the world is 'active', even though the button is displaying paused, but if you toggle on then off the 'open recent' world is actually paused and so none of the 'links' work. i can see why, but this isn't working smoothly.
