### ISSUE TITLE
[enhancement] allow sensor/interpolator nodes to be created directly.

### ISSUE THREAD

**Issue by splace** [create3000/titania#96]
no way to make interpolators either?

**Comment by splace** [comment]
no way to make interpolators either?

**Comment by create3000** [comment]
The preferred way to do that is to go to Projects & Files, there go to Library, select Components folder. There are all nodes you want, just double click and the node will be added to the scene graph.

**Comment by create3000** [comment]
To make interpolator nodes you also can use the Keyframe Animation Editor.

**Comment by splace** [comment]
so not possible ro create sensor/interpolator nodes using UI then.
