### ISSUE TITLE
[enhancement] allow routes to be deleted using delete key in out-line editor

### ISSUE THREAD

**Issue by splace** [create3000/titania#97]

**Comment by create3000** [comment]
Ctrl + click on a input/output connector (the triangle) should delete the route.

**Comment by splace** [comment]
not working for me.

**Comment by splace** [comment]
i have found it works using ctrl and clicking the half, the semi-circle, on the side that is being used.

but if you have fan-in/fan-out routes what happens?

since you can select the route line itself, why not just remove when that is clicked (or delete is pressed or context menu remove when selected?)
