### ISSUE TITLE
can add a route going back on itself, in out-line editor

### ISSUE THREAD

**Issue by splace** [create3000/titania#98]
![Screenshot from 2019-05-19 21:38:11](https://user-images.githubusercontent.com/1234848/57987806-b99c3180-7a7e-11e9-892c-bf8ae467ac44.png)

**Comment by create3000** [comment]
And you should also be able to delete this route.

**Comment by splace** [comment]
but confusing.

**Comment by splace** [comment]
thinking about it....

this is not just a nop, a function could be triggered by another function, in the same script, setting the outevent, but doesn't have a real use, other than to confuse, i can see.
